apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: uperf-server-{{ trunc_uuid }}
  namespace: {{ namespace }}
  labels:
    app: uperf-server-{{ trunc_uuid }}
    type: uperf-server-{{ trunc_uuid }}
    benchmark-uuid: {{ uuid }}
    benchmark-runner-workload: uperf
    role: server
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt-vm: uperf-server
        app: uperf-server-{{ trunc_uuid }}
    spec:
      {%- if pin == 'true' or pin == true %}
      nodeSelector:
        kubernetes.io/hostname: '{{ pin_server }}'
      {%- endif %}
      domain:
        cpu:
          sockets: {{ sockets }}
          cores: {{ cores }}
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: containerdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - name: default
              masquerade: {}
        machine:
          type: ""
        resources:
          requests:
            cpu: {{ requests_cpu }}
            memory: {{ requests_memory }}
          limits:
            cpu: {{ limits_cpu }}
            memory: {{ limits_memory }}
      terminationGracePeriodSeconds: 180
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: {{ fedora_container_disk }}
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              user: fedora
              password: fedora
              chpasswd: { expire: False }
              packages:
                - uperf
              runcmd:
                - uperf -s -v -P 30000 > /tmp/uperf_server.log 2>&1 &
                - sleep infinity
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: uperf-client-{{ trunc_uuid }}
  namespace: {{ namespace }}
  labels:
    app: uperf-client-{{ trunc_uuid }}
    type: uperf-client-{{ trunc_uuid }}
    benchmark-uuid: {{ uuid }}
    benchmark-runner-workload: uperf
    role: client
spec:
  runStrategy: Once
  template:
    metadata:
      labels:
        kubevirt-vm: uperf-client
        app: uperf-client-{{ trunc_uuid }}
    spec:
      {%- if pin == 'true' or pin == true %}
      nodeSelector:
        kubernetes.io/hostname: '{{ pin_client }}'
      {%- endif %}
      domain:
        cpu:
          sockets: {{ sockets }}
          cores: {{ cores }}
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: containerdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - name: default
              masquerade: {}
        machine:
          type: ""
        resources:
          requests:
            cpu: {{ requests_cpu }}
            memory: {{ requests_memory }}
          limits:
            cpu: {{ limits_cpu }}
            memory: {{ limits_memory }}
      terminationGracePeriodSeconds: 180
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: {{ fedora_container_disk }}
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              user: fedora
              password: fedora
              chpasswd: { expire: False }
              packages:
                - uperf
              write_files:
                - path: /tmp/test.xml
                  content: |
                    <?xml version="1.0"?>
                    <profile name="test">
                      <group nthreads="1">
                        <transaction iterations="1">
                          <flowop type="connect" options="remotehost={{ server_ip }} protocol=tcp tcp_nodelay"/>
                        </transaction>
                        <transaction duration="2">
                          <flowop type="write" options="size=64"/>
                        </transaction>
                        <transaction iterations="1">
                          <flowop type="disconnect"/>
                        </transaction>
                      </group>
                    </profile>
              runcmd:
                - sleep 30
                - uperf -m /tmp/test.xml -a -e -i 1 -P 30000 > /tmp/uperf.out 2>&1
                - touch /tmp/workload_complete.signal
