apiVersion: v1
kind: ConfigMap
metadata:
  name: uperf-test-{{ trunc_uuid }}
  namespace: {{ namespace }}
data:
{%- for test_type in test_types %}
{%- for proto in protos %}
{%- for size in sizes %}
{%- for nthr in nthrs %}
  uperf-{{ test_type }}-{{ proto }}-{{ size }}-{{ size }}-{{ nthr }}: |
    <?xml version=1.0?>
    <profile name="{{ test_type }}-{{ proto }}-{{ size }}-{{ size }}-{{ nthr }}">
    {%- if test_type == 'rr' %}
      <group nthreads="{{ nthr }}">
          <transaction iterations="1">
            <flowop type="connect" options="remotehost=SERVER_IP_PLACEHOLDER protocol={{ proto }} port=30001"/>
          </transaction>
          <transaction duration="{{ runtime }}">
            <flowop type=write options="size={{ size }}"/>
            <flowop type=read  options="size={{ size }}"/>
          </transaction>
          <transaction iterations="1">
            <flowop type=disconnect />
          </transaction>
      </group>
    {%- endif %}
    {%- if test_type == 'stream' or test_type == 'bidirec' %}
      <group nthreads="{{ nthr }}">
          <transaction iterations="1">
            <flowop type="connect" options="remotehost=SERVER_IP_PLACEHOLDER protocol={{ proto }} port=30001"/>
          </transaction>
          <transaction duration="{{ runtime }}">
            <flowop type=write options="count=16 size={{ size }}"/>
          </transaction>
          <transaction iterations="1">
            <flowop type=disconnect />
          </transaction>
      </group>
    {%- endif %}
    {%- if test_type == 'maerts' or test_type == 'bidirec' %}
      <group nthreads="{{ nthr }}">
          <transaction iterations="1">
            <flowop type="connect" options="remotehost=SERVER_IP_PLACEHOLDER protocol={{ proto }} port=30002"/>
          </transaction>
          <transaction duration="{{ runtime }}">
            <flowop type=read options="count=16 size={{ size }}"/>
          </transaction>
          <transaction iterations="1">
            <flowop type=disconnect />
          </transaction>
      </group>
    {%- endif %}
    </profile>
{%- endfor %}
{%- endfor %}
{%- endfor %}
{%- endfor %}
