{
 "title": "PerfCI-Regression-Summary",
 "time": { "from": "now-45d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ocp_version",
    "query": "{\"find\":\"terms\",\"field\":\"ocp_version.keyword\"}"
   },
   {
    "name": "vm_os_version",
    "query": "{\"find\":\"terms\",\"field\":\"vm_os_version.keyword\"}"
   },
   {
    "name": "db_type",
    "query": "{\"find\":\"terms\",\"field\":\"db_type.keyword\"}"
   },
   {
    "name": "current_worker",
    "query": "{\"find\":\"terms\",\"field\":\"current_worker\"}"
   },
   {
    "name": "kind",
    "query": "{\"find\":\"terms\",\"field\":\"kind.keyword\"}"
   },
   {
    "name": "vdbench_type",
    "query": "{\"find\":\"terms\",\"field\":\"Run.keyword\"}"
   },
   {
    "name": "fio_block_size",
    "query": "{\"find\":\"terms\",\"field\":\"block_size.keyword\"}"
   },
   {
    "name": "fio_io_operation",
    "query": "{\"find\":\"terms\",\"field\":\"io_operation.keyword\"}"
   },
   {
    "name": "vm_os_version",
    "query": "{\"find\":\"terms\",\"field\":\"vm_os_version.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Workloads Legend",
   "type": "text",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "\n<p style=\"background-color:#000099;text-align: center;\" > > 100% new peak</p>\n<p style=\"background-color:#006600;text-align: center;color:black;\" > 90% - 100% of peak</p>\n<p style=\"background-color:#9fdf9f;text-align: center;color:black;\" > 80% -  90% of peak</p>\n<p style=\"background-color:#cc6600;text-align: center;color:black;\" > 50% -  80% of peak</p>\n<p style=\"background-color:#992600;text-align: center;\" > 0%  -  50% of peak</p>\n\n\n           "
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "options": {
    "content": "![PerfCi](https://github.com/redhat-performance/benchmark-runner/blob/main/media/performance.png?raw=true \"Tooltip Text\")\n"
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Product Versions",
   "type": "state-timeline",
   "description": "OVN - 09/19",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "alias": "Openshift",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ci_minutes_time",
       "id": "1",
       "settings": {
        "script": "Integer.parseInt(\"0\"+doc[\"ocp_version.keyword\"].value.replace(\".\",\"\").replace(\"r\",\"1\").replace(\"e\",\"0\").replace(\"c\",\"\").replace(\"f\",\"\").replace(\"-\",\"\"))"
       },
       "type": "max"
      }
     ],
     "query": "_exists_:ocp_version AND ocp_version:$ocp_version",
     "timeField": "timestamp"
    },
    {
     "alias": "CNV Nightly op.",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ci_minutes_time",
       "id": "1",
       "settings": {
        "script": "(doc[\"cnv_version.keyword\"].value.indexOf(\" \") == -1) ? Integer.parseInt(\"0\"+doc[\"cnv_version.keyword\"].value.replace(\".\",\"\").replace(\"r\",\"\").replace(\"c\",\"\").replace(\"f\",\"\").replace(\"-\",\"\")) : 0"
       },
       "type": "max"
      }
     ],
     "query": "_exists_:cnv_version AND ocp_version:$ocp_version",
     "timeField": "timestamp"
    },
    {
     "alias": "ODF op.",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ci_minutes_time",
       "id": "1",
       "settings": {
        "script": "((doc[\"odf_version.keyword\"].size() != 0) ? ((doc[\"odf_version.keyword\"].value.indexOf(\" \") == -1) ? Integer.parseInt(\"0\"+doc[\"odf_version.keyword\"].value.replace(\".\",\"\").replace(\"r\",\"\").replace(\"c\",\"\").replace(\"f\",\"\").replace(\"-\",\"\").replace(\"v\",\"\").replace(\"o\",\"\").replace(\"d\",\"\").replace(\"p\",\"\").replace(\"e\",\"\").replace(\"a\",\"\").replace(\"t\",\"\").replace(\"s\",\"\").replace(\"b\",\"\").replace(\"l\",\"\")) : 0) : 0)"
       },
       "type": "max"
      }
     ],
     "query": "_exists_:odf_version AND ocp_version:$ocp_version",
     "timeField": "timestamp"
    },
    {
     "alias": "ODF # disks",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "odf_disk_count",
       "id": "1",
       "settings": {},
       "type": "max"
      }
     ],
     "query": "ocp_version:$ocp_version",
     "timeField": "timestamp"
    },
    {
     "alias": "Ci Status",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "status#",
       "id": "1",
       "settings": {},
       "type": "max"
      }
     ],
     "query": "ocp_version:$ocp_version",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Hammerdb",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "HammerDB KTPM",
     "type": "state-timeline",
     "description": "MSSQL2025 \n\nMariaDB10.11 \n\nPostgreSQL16\n\n HammerDB4.12",
     "gridPos": { "h": 38, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "alias": "{{term vm_os_version.keyword}}  : {{term db_type.keyword}}  : {{term current_worker}} threads : {{term kind.keyword}}:  {{term storage_type.keyword}}",
       "bucketAggs": [
        {
         "field": "db_type.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "current_worker",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "storage_type.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "vm_os_version.keyword",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "tpm", "id": "1", "settings": { "script": "_value/1000" }, "type": "max" }
       ],
       "query": "_exists_:tpm AND db_type:$db_type AND current_worker:$current_worker AND kind:$kind AND ocp_version:$ocp_version AND vm_os_version:$vm_os_version",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "HammerDB VM Memory",
     "type": "state-timeline",
     "description": "MariaDB: innodb_buffer_pool_size = 8GB \n\nPostgreSQL: shared_buffers = 4GB",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 51 },
     "targets": [
      {
       "alias": "{{term db_type.keyword}}  : {{field}} [GB]: {{term storage_type.keyword}}",
       "bucketAggs": [
        {
         "field": "db_type.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "storage_type.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "virt launcher Cache", "id": "1", "settings": { "script": "_value/1000000000" }, "type": "max" },
        {
         "field": "virt launcher working set bytes",
         "id": "2",
         "settings": { "script": "_value/1000000000" },
         "type": "max"
        }
       ],
       "query": "_exists_:tpm AND db_type:$db_type AND kind:vm AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Hammerdb Scale",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "HammerDB KTPM (Scale)",
     "type": "state-timeline",
     "description": "HammerDB Scale: KTPM per VM\nLinux: hammerdb_vm_mssql_scale\nWindows: winmssql_vm_scale",
     "gridPos": { "h": 38, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "alias": "{{term vm_os_version.keyword}} : {{term vm_name_num.keyword}} : {{term db_type.keyword}}",
       "bucketAggs": [
        {
         "field": "vm_name_num.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "50" },
         "type": "terms"
        },
        {
         "field": "db_type.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "vm_os_version.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "tpm", "id": "1", "settings": { "script": "_value/1000" }, "type": "avg" }
       ],
       "query": "_exists_:scale AND _exists_:vm_name_num AND _exists_:tpm AND ocp_version:$ocp_version AND vm_os_version:$vm_os_version",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Uperf",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uperf Latency (usecs)",
     "type": "state-timeline",
     "description": "Lower is better (P95)",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 52 },
     "targets": [
      {
       "alias": "msg size: {{term read_message_size}} :{{term num_threads}}th: {{term kind.keyword}}",
       "bucketAggs": [
        {
         "field": "read_message_size",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "num_threads",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "norm_ltcy",
         "id": "1",
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "_exists_:norm_ltcy AND read_message_size:(64 OR 1024 OR 8192) AND num_threads:(1 OR 8) AND test_type:rr AND norm_ltcy:<1000 AND kind:$kind AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Uperf Throughput (Gbits/s)",
     "type": "state-timeline",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 67 },
     "targets": [
      {
       "alias": "msg size: {{term read_message_size}} :{{term num_threads}}th: {{term kind.keyword}}",
       "bucketAggs": [
        {
         "field": "read_message_size",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "num_threads",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "norm_byte", "id": "1", "settings": { "script": "_value*8/1000000000" }, "type": "avg" }
       ],
       "query": "_exists_:norm_ops AND read_message_size:(64 OR 1024 OR 8192) AND num_threads:(1 OR 8) AND test_type:stream AND kind:$kind AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Uperf VM Memory",
     "type": "state-timeline",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 67 },
     "targets": [
      {
       "alias": "{{field}} [GB]",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "virt launcher Cache", "id": "1", "settings": { "script": "_value/1000000000" }, "type": "max" },
        {
         "field": "virt launcher working set bytes",
         "id": "2",
         "settings": { "script": "_value/1000000000" },
         "type": "max"
        }
       ],
       "query": "_exists_:norm_ops AND kind:vm AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Sysbench",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sysbench CPU Events (avg)",
     "type": "state-timeline",
     "description": "Higher is better",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "alias": "{{term kind.keyword}}",
       "bucketAggs": [
        {
         "field": "kind.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "cpu_events_avg",
         "id": "1",
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "_exists_:cpu_events_avg AND kind:$kind AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Sysbench CPU Latency P95 (ms)",
     "type": "state-timeline",
     "description": "Lower is better",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "alias": "{{term kind.keyword}}",
       "bucketAggs": [
        {
         "field": "kind.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "cpu_latency_95th",
         "id": "1",
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "_exists_:cpu_latency_95th AND kind:$kind AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Sysbench Memory Throughput (MiB/s)",
     "type": "state-timeline",
     "description": "Higher is better",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "alias": "{{term kind.keyword}}",
       "bucketAggs": [
        {
         "field": "kind.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "memory_throughput_mib",
         "id": "1",
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "_exists_:memory_throughput_mib AND kind:$kind AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Sysbench Memory Latency P95 (ms)",
     "type": "state-timeline",
     "description": "Lower is better",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 45 },
     "targets": [
      {
       "alias": "{{term kind.keyword}}",
       "bucketAggs": [
        {
         "field": "kind.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "memory_latency_95th",
         "id": "1",
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "_exists_:memory_latency_95th AND kind:$kind AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Vdbench",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "vdbench (IOPS)",
     "type": "state-timeline",
     "gridPos": { "h": 48, "w": 24, "x": 0, "y": 83 },
     "targets": [
      {
       "alias": "{{term Run.keyword}} : {{term Threads}}th : 1 {{term kind.keyword}}",
       "bucketAggs": [
        {
         "field": "Run.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "Threads",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "5",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "Rate", "id": "1", "type": "avg" }
       ],
       "query": "!SCALE AND !Run.keyword='fillup' AND kind:$kind AND Run:$vdbench_type AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "Total %CPU [240 cores]: 1 {{term kind.keyword}}",
       "bucketAggs": [
        {
         "field": "kind.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "5",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "total_CPU", "id": "1", "type": "max" }
       ],
       "query": "!SCALE AND !Run.keyword='fillup' AND kind:$kind AND Run:$vdbench_type AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "{{term Run.keyword}} : {{term Threads}}th :{{term scale}} {{term kind.keyword}}s",
       "bucketAggs": [
        {
         "field": "Run.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "Threads",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "scale",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "5",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "Rate", "id": "1", "type": "avg" }
       ],
       "query": "SCALE AND !Run.keyword='fillup' AND kind:$kind AND Run:$vdbench_type AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "Total %CPU [240 cores]: {{term scale}} {{term kind.keyword}}",
       "bucketAggs": [
        {
         "field": "kind.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "scale",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "5",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "total_CPU",
         "id": "1",
         "settings": {},
         "type": "max"
        }
       ],
       "query": "SCALE AND !Run.keyword='fillup' AND kind:$kind AND Run:$vdbench_type AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "vdbench Latency (sec)",
     "type": "state-timeline",
     "description": "Lower is better",
     "gridPos": { "h": 50, "w": 24, "x": 0, "y": 131 },
     "targets": [
      {
       "alias": "{{term Run.keyword}} : {{term Threads}}th : 1 {{term kind.keyword}}",
       "bucketAggs": [
        {
         "field": "Run.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "Threads",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "5",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "Resp", "id": "1", "type": "avg" }
       ],
       "query": "!SCALE AND !Run.keyword='fillup' AND kind:$kind AND Run:$vdbench_type AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "Total %CPU [240 cores]: 1 {{term kind.keyword}}",
       "bucketAggs": [
        {
         "field": "kind.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "5",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "total_CPU",
         "id": "1",
         "settings": {},
         "type": "max"
        }
       ],
       "query": "!SCALE AND !Run.keyword='fillup' AND kind:$kind AND Run:$vdbench_type AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "{{term Run.keyword}} : {{term Threads}}th :{{term scale}} {{term kind.keyword}}s",
       "bucketAggs": [
        {
         "field": "Run.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "Threads",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "scale",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "5",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "Resp", "id": "1", "type": "avg" }
       ],
       "query": "SCALE AND !Run.keyword='fillup' AND kind:$kind AND Run:$vdbench_type AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "Total %CPU [240 cores]: {{term scale}} {{term kind.keyword}}",
       "bucketAggs": [
        {
         "field": "kind.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "scale",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "5",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "total_CPU",
         "id": "1",
         "settings": {},
         "type": "max"
        }
       ],
       "query": "SCALE AND !Run.keyword='fillup' AND kind:$kind AND Run:$vdbench_type AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "vdbench VM memory",
     "type": "state-timeline",
     "description": "Lower is better",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 131 },
     "targets": [
      {
       "alias": "{{field}} [GB]: 1 vm",
       "bucketAggs": [
        {
         "field": "kind.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "5",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "virt launcher Cache", "id": "1", "settings": { "script": "_value/1000000000" }, "type": "max" },
        {
         "field": "virt launcher working set bytes",
         "id": "2",
         "settings": { "script": "_value/1000000000" },
         "type": "max"
        }
       ],
       "query": "!SCALE AND !Run.keyword='fillup' AND kind:'vm' AND Run:$vdbench_type AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "{{field}} [GB]: {{term scale}} {{kind.keyword}}s",
       "bucketAggs": [
        {
         "field": "scale",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "5",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "virt launcher Cache", "id": "1", "settings": { "script": "_value/1000000000" }, "type": "max" },
        {
         "field": "virt launcher working set bytes",
         "id": "2",
         "settings": { "script": "_value/1000000000" },
         "type": "max"
        }
       ],
       "query": "SCALE AND !Run.keyword='fillup' AND kind:'vm' AND Run:$vdbench_type AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "FIO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "FIO (IOPS)",
     "type": "state-timeline",
     "gridPos": { "h": 36, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "alias": "{{term vm_os_version.keyword}} : {{term block_size.keyword}} : {{term io_operation.keyword}} : 1 {{term kind.keyword}}",
       "bucketAggs": [
        {
         "field": "block_size.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "io_operation.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "vm_os_version.keyword",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "5",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "total_iops", "id": "1", "type": "avg" }
       ],
       "query": "!scale AND kind:$kind AND block_size:$fio_block_size AND io_operation:$fio_io_operation AND ocp_version:$ocp_version AND vm_os_version:$vm_os_version",
       "timeField": "timestamp"
      },
      {
       "alias": "{{term vm_os_version.keyword}} : {{term block_size.keyword}} : {{term io_operation.keyword}} : {{term scale}} {{term kind.keyword}}s",
       "bucketAggs": [
        {
         "field": "block_size.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "io_operation.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "scale",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "vm_os_version.keyword",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "5",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "total_iops", "id": "1", "settings": { "script": "_value*6" }, "type": "avg" }
       ],
       "query": "scale AND kind:$kind AND block_size:$fio_block_size AND io_operation:$fio_io_operation AND ocp_version:$ocp_version AND vm_os_version:$vm_os_version",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FIO Latency (usec)",
     "type": "state-timeline",
     "description": "Lower is better",
     "gridPos": { "h": 36, "w": 24, "x": 0, "y": 52 },
     "targets": [
      {
       "alias": "{{term vm_os_version.keyword}} : {{term block_size.keyword}} : {{term io_operation.keyword}} : 1 {{term kind.keyword}}",
       "bucketAggs": [
        {
         "field": "block_size.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "io_operation.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "vm_os_version.keyword",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "5",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "lat_avg_usec", "id": "1", "type": "avg" }
       ],
       "query": "!scale AND kind:$kind AND block_size:$fio_block_size AND io_operation:$fio_io_operation AND ocp_version:$ocp_version AND vm_os_version:$vm_os_version",
       "timeField": "timestamp"
      },
      {
       "alias": "{{term vm_os_version.keyword}} : {{term block_size.keyword}} : {{term io_operation.keyword}} : {{term scale}} {{term kind.keyword}}s",
       "bucketAggs": [
        {
         "field": "block_size.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "io_operation.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "scale",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "vm_os_version.keyword",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "5",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "lat_avg_usec", "id": "1", "type": "avg" }
       ],
       "query": "scale AND kind:$kind AND block_size:$fio_block_size AND io_operation:$fio_io_operation AND ocp_version:$ocp_version AND vm_os_version:$vm_os_version",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "BootStorm",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "240 Fedora43 VMs(Sec)",
     "type": "state-timeline",
     "description": "Time till VM Login - Lower is better",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 187 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Min",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "bootstorm_time", "id": "1", "settings": { "script": "_value/1000" }, "type": "min" }
       ],
       "query": "scale:240 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "bootstorm_time",
         "id": "1",
         "settings": {
          "percents": [
           "50",
           "90"
          ],
          "script": "_value/1000"
         },
         "type": "percentiles"
        }
       ],
       "query": "scale:240 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "Max",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "bootstorm_time", "id": "1", "settings": { "script": "_value/1000" }, "type": "max" }
       ],
       "query": "scale:240 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "{{field}} (min.)",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "total_run_time", "id": "1", "settings": { "script": "_value/1000/60" }, "type": "max" }
       ],
       "query": "scale:240 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "type": "state-timeline",
     "description": "Time till VM Login - Lower is better",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 187 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "VMs #: Fedora",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "scale:240 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "240 Fedora43 VM Memory",
     "type": "state-timeline",
     "description": "Time till VM Login - Lower is better",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 187 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "{{field}} [GB]",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "virt launcher Cache", "id": "1", "settings": { "script": "_value/1000000000" }, "type": "max" },
        {
         "field": "virt launcher working set bytes",
         "id": "2",
         "settings": { "script": "_value/1000000000" },
         "type": "max"
        }
       ],
       "query": "scale:240 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "111 Windows VMs virtio (Sec)",
     "type": "state-timeline",
     "description": "Time till VM Login - Lower is better [changed to 111 vms in 01/07/2024]",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 206 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Min: {{term vm_os_version.keyword}}",
       "bucketAggs": [
        {
         "field": "vm_os_version.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "bootstorm_time", "id": "1", "settings": { "script": "_value/1000" }, "type": "min" }
       ],
       "query": "scale:111 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "bucketAggs": [
        {
         "field": "vm_os_version.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "bootstorm_time",
         "id": "1",
         "settings": {
          "percents": [
           "50",
           "90"
          ],
          "script": "_value/1000"
         },
         "type": "percentiles"
        }
       ],
       "query": "scale:111 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "Max: {{term vm_os_version.keyword}}",
       "bucketAggs": [
        {
         "field": "vm_os_version.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "bootstorm_time", "id": "1", "settings": { "script": "_value/1000" }, "type": "max" }
       ],
       "query": "scale:111 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "{{field}} {{term vm_os_version.keyword}} (min.)",
       "bucketAggs": [
        {
         "field": "vm_os_version.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "total_run_time", "id": "1", "settings": { "script": "_value/1000/60" }, "type": "max" }
       ],
       "query": "scale:111 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "type": "state-timeline",
     "description": "Time till VM Login - Lower is better",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 206 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "VMs #: {{term vm_os_version.keyword}}",
       "bucketAggs": [
        {
         "field": "vm_os_version.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "scale:111 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "111 Windows VM Memory",
     "type": "state-timeline",
     "description": "Time till VM Login - Lower is better",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 206 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "{{field}} [GB]: {{term vm_os_version.keyword}}",
       "bucketAggs": [
        {
         "field": "vm_os_version.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "virt launcher Cache", "id": "1", "settings": { "script": "_value/1000000000" }, "type": "max" },
        {
         "field": "virt launcher working set bytes",
         "id": "2",
         "settings": { "script": "_value/1000000000" },
         "type": "max"
        }
       ],
       "query": "scale:111 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Artifacts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "HammerDB artifacts",
     "type": "table",
     "gridPos": { "h": 28, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "ci_date.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "db_type.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "current_worker",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "storage_type.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "run_artifacts_url.keyword",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "tpm", "id": "1", "settings": { "script": "_value/1000" }, "type": "max" }
       ],
       "query": "_exists_:tpm AND db_type:$db_type AND current_worker:$current_worker AND kind:$kind",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Uperf artifacts",
     "type": "table",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 50 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "ci_date.keyword",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "5" },
         "type": "terms"
        },
        {
         "field": "read_message_size",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "num_threads",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "run_artifacts_url.keyword",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "norm_byte", "id": "1", "settings": { "script": "_value*8/1000000000" }, "type": "avg" }
       ],
       "query": "_exists_:norm_ops AND read_message_size:(64 OR 1024 OR 8192) AND num_threads:(1 OR 8) AND test_type:stream",
       "timeField": "uperf_ts"
      }
     ]
    },
    {
     "title": "vdbench artifacts",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 65 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "ci_date.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "5" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "run_artifacts_url.keyword",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "Rate", "id": "1", "type": "avg" }
       ],
       "query": "!SCALE AND !Run.keyword='fillup'",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "vdbench scale artifacts",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 75 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "ci_date.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "5" },
         "type": "terms"
        },
        {
         "field": "Run.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "Threads",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "scale",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "run_artifacts_url.keyword",
         "id": "9",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "Rate", "id": "1", "type": "avg" }
       ],
       "query": "!Run.keyword='fillup'",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "clusterbuster artifacts",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 85 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "run_artifacts_url.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "job_runtime",
         "hide": false,
         "id": "1",
         "type": "avg"
        }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "clusterbuster release artifacts",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 91 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "run_artifacts_url.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "job_runtime",
         "hide": false,
         "id": "1",
         "type": "avg"
        }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "bootstorm artifacts",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 97 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "ci_date.keyword",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "9",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "scale",
         "id": "100",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "run_artifacts_url.keyword",
         "id": "11",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "Rate", "id": "1", "type": "avg" }
       ],
       "query": "scale:240",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Windows artifacts",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 102 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "ci_date.keyword",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "9",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "scale",
         "id": "10",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "vm_os_version.keyword",
         "id": "11",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "run_artifacts_url.keyword",
         "id": "12",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "Rate", "id": "1", "type": "avg" }
       ],
       "query": "scale:(111 OR 120)",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 107 },
     "options": {
      "content": "![Cloud Governance](https://github.com/redhat-performance/benchmark-runner/blob/main/media/benchmark_runner.png?raw=true \"Tooltip Text\")\n"
     },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    }
   ]
  }
 ]
}