apiVersion: v1
kind: Namespace
metadata:
  name: {{ namespace }}
{%- if ocs_pvc == True %}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vdbench-pvc
  namespace: {{ namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ocs-storagecluster-ceph-rbd
  resources:
    requests:
      storage: {{ storage }}
{%- endif %}
---
kind: Pod
apiVersion: v1
metadata:
  name: vdbench-{{ kind }}-{{ trunc_uuid }}
  namespace: {{ namespace }}
  labels:
    app: vdbench-{{ trunc_uuid }}
    type: vdbench-{{ kind }}-{{ trunc_uuid }}
    benchmark-uuid: {{ uuid }}
    benchmark-runner-workload: vdbench
spec:
  selector:
    matchLabels:
      app: vdbench
  {%- if pin_node != '' %}
  nodeSelector:
    kubernetes.io/hostname: {{ pin_node1 }}
  {%- endif %}
  {%- if kind == 'kata' %}
  runtimeClassName: kata
  {%- endif %}
  containers:
    - name: vdbench-pod
      namespace: {{ namespace }}
      image: quay.io/bbenshab/vdpod
      imagePullPolicy: "IfNotPresent"
      {%- if ocs_pvc == True %}
      volumeMounts:
        - name: vdbench-pvc
          mountPath: "/workload"
      {%- endif %}
      env:
        - name: BLOCK_SIZES
          value: "{{ BLOCK_SIZES }}"
        - name: IO_OPERATION
          value: "{{ IO_OPERATION }}"
        - name: IO_THREADS
          value: "{{ IO_THREADS }}"
        - name: FILES_IO #How file IO will be done
          value: "{{ FILES_IO }}"
        - name: IO_RATE # an integer or "max"
          value: "{{ IO_RATE }}"
        - name: MIX_PRECENTAGE # used for mixed workload 0-100
          value:
        #global settings
        - name: DURATION
          value: "{{ DURATION }}"
        - name: PAUSE #pause after every test in sec
          value: "{{ PAUSE }}"
        - name: WARMUP # warmup before any test in sec
          value: "{{ WARMUP }}"
        - name: FILES_SELECTION #This parameter allows you to select directories and files for processing either sequential/random
          value: "{{ FILES_SELECTION }}"
        - name: COMPRESSION_RATIO #ratio is 1:X e.g 2 = 50% compressible
          value: "{{ COMPRESSION_RATIO }}"
        - name: RUN_FILLUP #will it run a fillup before testing starts yes/no
          value: "{{ RUN_FILLUP }}"
        #data set settings
        - name: DIRECTORIES #how many directories to create
          value: "{{ DIRECTORIES }}"
        - name: FILES_PER_DIRECTORY
          value: "{{ FILES_PER_DIRECTORY }}"
        - name: SIZE_PER_FILE # size in MB
          value: "{{ SIZE_PER_FILE }}"
      command: ["/bin/bash"]
      args: ["-c", "/vdbench/vdbench_runner.sh"]
  restartPolicy: "Never"
  spec:
    pvc:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: {{ storage }}
          Reclaim Policy: Delete
      storageClassName: ocs-storagecluster-ceph-rbd
    source:
      blank: {}
  {%- if ocs_pvc == True %}
  volumes:
    - name: vdbench-pvc
      namespace: {{ namespace }}
      persistentVolumeClaim:
        claimName: vdbench-pvc
  {%- endif %}
  resources:
    requests:
      cpu: {{ requests_cpu }}
      memory: {{ requests_memory }}
    limits:
      cpu: {{ limits_cpu }}
      memory: {{ limits_memory }}
