{% if not scale %}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ namespace }}
{%- endif %}
{%- if odf_pvc == True %}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  {% if not scale -%}
  name: vdbench-pvc-claim
  {%- else -%}
  name: vdbench-pvc-claim-{{ scale }}
  {%- endif %}
  namespace: {{ namespace }}
spec:
  storageClassName: ocs-storagecluster-ceph-rbd
  accessModes: [ "ReadWriteOnce" ]
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ storage }}
{%- endif %}
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  {% if not scale -%}
  name: vdbench-{{ kind }}-{{ trunc_uuid }}
  {%- else -%}
  name: vdbench-{{ kind }}-{{ trunc_uuid }}-{{ scale }}
  {%- endif %}
  namespace: {{ namespace }}
  labels:
    {% if not scale -%}
    app: vdbench-{{ trunc_uuid }}
    type: vdbench-{{ kind }}-{{ trunc_uuid }}
    {%- else -%}
    app: vdbench-{{ trunc_uuid }}-{{ scale }}
    type: vdbench-{{ kind }}-{{ trunc_uuid }}-{{ scale }}
    {%- endif %}
    benchmark-uuid: {{ uuid }}
    benchmark-runner-workload: vdbench
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt-vm: vdbench
    spec:
      {%- if pin_node1 or scale_node %}
      nodeSelector:
        {% if not scale -%}
        kubernetes.io/hostname: {{ pin_node1 }}
        {%- else -%}
        kubernetes.io/hostname: {{ scale_node }}
        {%- endif %}
      {%- endif %}
      domain:
        cpu:
          sockets: {{ sockets }}
          cores: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: containerdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
            - disk:
                bus: virtio
              name: data-volume
              serial: vdbenchdata
        machine:
          type: ""
        resources:
          requests:
            cpu: {{ requests_cpu }}
            memory: {{ requests_memory }}
          limits:
            cpu: {{ limits_cpu }}
            memory: {{ limits_memory }}
      terminationGracePeriodSeconds: 0
      volumes:
{%- if odf_pvc == True %}
        - name: data-volume
          persistentVolumeClaim:
            {% if not scale -%}
            claimName: vdbench-pvc-claim
            {%- else -%}
            claimName: vdbench-pvc-claim-{{ scale }}
            {%- endif %}
{%- endif %}
        - containerDisk:
            image: quay.io/ebattat/centos-stream8-vdbench5.04.07-container-disk:v1.0.11
          name: containerdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              password: centos
              chpasswd: { expire: False }
              bootcmd:
                - "mkdir -p /workload || true"
                - "[ -e /dev/disk/by-id/*vdbenchdata ] && disk=$(shopt -s nullglob; basename /dev/disk/by-id/*vdbenchdata) && mkfs.ext4 /dev/disk/by-id/$disk && mount /dev/disk/by-id/$disk /workload"
              runcmd:
                - export BLOCK_SIZES={{ BLOCK_SIZES }}
                - export IO_OPERATION={{ IO_OPERATION }}
                - export IO_THREADS={{ IO_THREADS }}
                - export FILES_IO={{ FILES_IO }}
                - export IO_RATE={{ IO_RATE }}
                - export MIX_PRECENTAGE # used for mixed workload 0-100
                - export DURATION={{ DURATION }}
                - export PAUSE={{ PAUSE }}
                - export WARMUP={{ WARMUP }}
                - export FILES_SELECTION={{ FILES_SELECTION }}
                - export COMPRESSION_RATIO={{ COMPRESSION_RATIO }}
                - export RUN_FILLUP={{ RUN_FILLUP }}
                - export DIRECTORIES={{ DIRECTORIES }}
                - export FILES_PER_DIRECTORY={{ FILES_PER_DIRECTORY }}
                - export SIZE_PER_FILE={{ SIZE_PER_FILE }}
                - export REDIS_HOST={{ redis }}
                - export WORKLOAD_METHOD="/vdbench/vdbench_runner.sh"
                - export TIMEOUT={{ timeout }}
                - echo @@~@@START-WORKLOAD@@~@@
                {% if not scale -%}
                - /vdbench/vdbench_runner.sh
                {%- else -%}
                - python3.9 /state_signals_responder.py $REDIS_HOST $WORKLOAD_METHOD $TIMEOUT
                {%- endif %}
                - echo @@~@@END-WORKLOAD@@~@@
          name: cloudinitdisk
