{
 "title": "regression-summery",
 "time": { "from": "now-45d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ocp_version",
    "label": "ocp_version",
    "query": "{\"find\":\"terms\",\"field\":\"ocp_version.keyword\"}"
   },
   {
    "name": "db_type",
    "query": "{\"find\":\"terms\",\"field\":\"db_type.keyword\"}"
   },
   {
    "name": "current_worker",
    "query": "{\"find\":\"terms\",\"field\":\"current_worker\"}"
   },
   {
    "name": "kind",
    "query": "{\"find\":\"terms\",\"field\":\"kind.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "benchmark-runner/ benchmark-operator ci status",
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 0 },
   "options": {
    "content": "![alt text](https://github.com/redhat-performance/benchmark-runner/blob/main/media/benchmark_runner.png?raw=true \"Tooltip Text\")"
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Product Version Numbers",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "alias": "ocp_version",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ci_minutes_time",
       "id": "1",
       "settings": {
        "script": "Integer.parseInt(\"0\"+doc['ocp_version.keyword'].value.replace(\".\",\"\").replace(\"r\",\"\").replace(\"c\",\"\").replace(\"f\",\"\").replace(\"-\",\"\"))"
       },
       "type": "max"
      }
     ],
     "query": "_exists_:ocp_version",
     "timeField": "timestamp"
    },
    {
     "alias": "odf_version",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ci_minutes_time",
       "id": "1",
       "settings": {
        "script": "Integer.parseInt(\"0\"+doc['odf_version.keyword'].value.replace(\".\",\"\").replace(\"r\",\"\").replace(\"c\",\"\").replace(\"f\",\"\").replace(\"-\",\"\"))"
       },
       "type": "max"
      }
     ],
     "query": "_exists_:odf_version",
     "timeField": "timestamp"
    },
    {
     "alias": "cnv_version",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ci_minutes_time",
       "id": "1",
       "settings": {
        "script": "(doc['cnv_version.keyword'].value.indexOf(\" \") == -1) ? Integer.parseInt(\"0\"+doc['cnv_version.keyword'].value.replace(\".\",\"\").replace(\"r\",\"\").replace(\"c\",\"\").replace(\"f\",\"\").replace(\"-\",\"\")) : 0"
       },
       "type": "max"
      }
     ],
     "query": "_exists_:cnv_version",
     "timeField": "timestamp"
    },
    {
     "alias": "kata_version",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ci_minutes_time",
       "id": "1",
       "settings": {
        "script": "Integer.parseInt(\"0\"+doc['kata_version.keyword'].value.replace(\".\",\"\").replace(\"r\",\"\").replace(\"c\",\"\").replace(\"f\",\"\").replace(\"-\",\"\"))"
       },
       "type": "max"
      }
     ],
     "query": "_exists_:kata_version",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Hammerdb",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hammerdb (KTPM)",
     "type": "state-timeline",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "alias": "{{term db_type.keyword}} workers={{term current_worker}} {{term kind.keyword}} {{term storage_type.keyword}}",
       "bucketAggs": [
        {
         "field": "db_type.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "current_worker",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "storage_type.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "tpm", "id": "1", "settings": { "script": "_value/1000" }, "type": "max" }
       ],
       "query": "_exists_:tpm AND db_type:$db_type AND current_worker:$current_worker AND kind:$kind",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Uperf",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uperf Gbits/s",
     "type": "state-timeline",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "alias": "msg size: {{term read_message_size}} :{{term num_threads}}th: {{term kind.keyword}}",
       "bucketAggs": [
        {
         "field": "read_message_size",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "num_threads",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "norm_byte", "id": "1", "settings": { "script": "_value*8/1000000000" }, "type": "avg" }
       ],
       "timeField": "uperf_ts"
      }
     ]
    },
    {
     "title": "Uperf latency (usecs)",
     "type": "state-timeline",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "alias": "msg size: {{term read_message_size}} :{{term num_threads}}th: {{term kind.keyword}}",
       "bucketAggs": [
        {
         "field": "read_message_size",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "num_threads",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "norm_ltcy",
         "id": "1",
         "settings": {},
         "type": "avg"
        }
       ],
       "timeField": "uperf_ts"
      }
     ]
    }
   ]
  },
  {
   "title": "ClusterBuster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Clusterbuster: cpusoaker",
     "type": "state-timeline",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "alias": "Max {{term test_description.runtime.keyword}}",
       "bucketAggs": [
        {
         "field": "test_description.runtime.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "test_description.pods", "id": "1", "type": "max" }
       ],
       "timeField": "timestamp"
      },
      {
       "alias": "Memory (MB) Max {{term test_description.runtime.keyword}}",
       "bucketAggs": [
        {
         "field": "test_description.runtime.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "memory_per_pod", "id": "4", "settings": { "script": "_value/1000000" }, "type": "max" }
       ],
       "timeField": "timestamp"
      },
      {
       "alias": "Start time(sec):  {{term test_description.runtime.keyword}}",
       "bucketAggs": [
        {
         "field": "test_description.runtime.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "pod_starts_per_second", "id": "4", "settings": { "script": "_value" }, "type": "max" }
       ],
       "timeField": "timestamp"
      },
      {
       "alias": "Iteration cpu sec:  {{term test_description.runtime.keyword}}",
       "bucketAggs": [
        {
         "field": "test_description.runtime.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "iterations_cpu_sec", "id": "4", "settings": { "script": "_value/1000000" }, "type": "max" }
       ],
       "timeField": "timestamp"
      },
      {
       "alias": "Iteration sec:  {{term test_description.runtime.keyword}}",
       "bucketAggs": [
        {
         "field": "test_description.runtime.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "iterations_sec", "id": "4", "settings": { "script": "_value/1000000" }, "type": "max" }
       ],
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Vdbench",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Vdbench",
     "type": "state-timeline",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 46 },
     "targets": [
      {
       "alias": " run:{{term Run.keyword}} :{{term kind.keyword}}: {{term Threads}}th",
       "bucketAggs": [
        {
         "field": "Run.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "Threads",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "Rate", "id": "1", "type": "avg" }
       ],
       "query": "!SCALE AND !Run.keyword='fillup'",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "CI Status",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "ci_date.keyword",
         "id": "12",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "status.keyword",
         "id": "15",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "runner_version.keyword",
         "id": "17",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "ocp_version.keyword",
         "id": "18",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "cnv_version.keyword",
         "id": "19",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "odf_version.keyword",
         "id": "20",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kata_version.keyword",
         "id": "21",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "benchmark_operator_id.keyword",
         "id": "22",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "benchmark_wrapper_id.keyword",
         "id": "23",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "24",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "ci_minutes_time",
         "id": "25",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "version",
         "hide": true,
         "id": "1",
         "settings": {},
         "type": "max"
        }
       ],
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Run artifacts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Artifacts",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "ci_date.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "db_type.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "current_worker",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "storage_type.keyword",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "run_artifacts_url.keyword",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "tpm", "id": "1", "settings": { "script": "_value/1000" }, "type": "max" }
       ],
       "query": "_exists_:tpm AND db_type:$db_type AND current_worker:$current_worker AND kind:$kind",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  }
 ]
}