apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: stressng
  namespace: my-ripsaw
spec:
  elasticsearch:
    url: {{ url }}
    index_name: {{ index_name }}
  metadata:
    collection: false
  workload:
    name: stressng
    args:
      pin: {{ pin }} # enable for nodeSelector
      pin_client: "{{ pin_client }}"
      resources: {{ resources }} # enable for resources requests/limits
      requests_cpu: 200m
      requests_memory: 100Mi
      limits_cpu: {{ limits_cpu }}
      limits_memory: {{ limits_memory_GB }}Gi
      # general options
      runtype: "{{ runtype }}"
      timeout: "{{ timeout }}"
      instances: {{ instances }}
      # cpu stressor options
      cpu_stressors: "{{ cpu_stressors }}"
      cpu_percentage: "{{ cpu_percentage }}"
      # vm stressor option
      vm_stressors: "{{ vm_stressors }}"
      vm_bytes: "{{ vm_bytes }}"
      # mem stressor options
      mem_stressors: "{{ mem_stressors }}"
