{
 "title": "benchmark-runner-summary-line-report-final",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ocp_version",
    "label": "ocp_version",
    "query": "{\"find\":\"terms\",\"field\":\"ocp_version.keyword\"}"
   }
  ]
 },
 "panels": [
  { "title": "Hammerdb Mariadb", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Hammerdb_workers" },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "![alt text](https://github.com/redhat-performance/benchmark-runner/blob/main/media/mariadb.png?raw=true \"Tooltip Text\")"
   }
  },
  {
   "title": "Mariadb TPM ",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "alias": "pod 1W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mariadb' AND current_worker:1 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 1W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:1 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 1W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:1 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 2W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mariadb' AND current_worker:2 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 2W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 2W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 4W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mariadb' AND current_worker:4 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 4W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:4 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 4W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:4 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 8W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mariadb' AND current_worker:8 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 8W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:8 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 8W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:8 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 16W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mariadb' AND current_worker:16 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 16W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:16 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 16W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:16 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 32W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mariadb' AND current_worker:32 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 32W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:32 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 32W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:32 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Mariadb (state timeline)",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "alias": "pod 1W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mariadb' AND current_worker:1 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 1W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:1 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 1W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:1 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 2W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mariadb' AND current_worker:2 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 2W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 2W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 4W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mariadb' AND current_worker:4 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 4W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:4 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 4W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:4 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 8W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mariadb' AND current_worker:8 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 8W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:8 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 8W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:8 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 16W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mariadb' AND current_worker:16 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 16W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:16 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 16W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:16 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 32W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mariadb' AND current_worker:32 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 32W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:32 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 32W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:32 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Hammerdb mariaDB run artifacts",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "run_artifacts_url.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "version", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mariadb'",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Hammerdb PostgresSQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 }, "repeat": "Hammerdb_workers" },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "options": {
    "content": "![alt text](https://github.com/redhat-performance/benchmark-runner/blob/main/media/postgresql.png?raw=true \"Tooltip Text\")"
   }
  },
  {
   "title": "PostgresSQL TPM",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "alias": "pod 1W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'pg' AND current_worker:1 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 1W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:1 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 1W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:1 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 2W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'pg' AND current_worker:2 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 2W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:2 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 2W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:2 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 4W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'pg' AND current_worker:4 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 4W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:4 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 4W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:4 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 8W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'pg' AND current_worker:8 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 8W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:8 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 8W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:8 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 16W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'pg' AND current_worker:16 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 16W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:16 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 16W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:16 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 32W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'pg' AND current_worker:32 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 32W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:32 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 32W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:32 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "PostgresSQL (state timeline)",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "alias": "pod 1W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'pg' AND current_worker:1 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 1W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:1 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 1W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:1 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 2W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'pg' AND current_worker:2 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 2W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:2 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 2W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:2 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 4W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'pg' AND current_worker:4 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 4W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:4 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 4W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:4 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 8W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'pg' AND current_worker:8 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 8W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:8 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 8W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:8 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 16W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'pg' AND current_worker:16 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 16W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:16 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 16W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:16 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 32W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'pg' AND current_worker:32 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 32W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:32 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 32W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:32 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Hammerdb PostgreSQL run artifacts",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "run_artifacts_url.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "version", "id": "1", "type": "max" }
     ],
     "query": "db_type:'pg'",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Hammerdb MSSQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 }, "repeat": "Hammerdb_workers" },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 68 },
   "options": {
    "content": "![alt text](https://github.com/redhat-performance/benchmark-runner/blob/main/media/mssql.png?raw=true \"Tooltip Text\")"
   }
  },
  {
   "title": "MSSQL TPM",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {
     "alias": "pod 1W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mssql' AND current_worker:1 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 1W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:1 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 1W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:1 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 2W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mssql' AND current_worker:2 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 2W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:2 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 2W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:2 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 4W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mssql' AND current_worker:4 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 4W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:4 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 4W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:4 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 8W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mssql' AND current_worker:8 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 8W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:8 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 8W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:8 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 16W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mssql' AND current_worker:16 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 16W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:16 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 16W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:16 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 32W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mssql' AND current_worker:32 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 32W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:32 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 32W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:32 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "MSSQL (state timeline)",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {
     "alias": "pod 1W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mssql' AND current_worker:1 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 1W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:1 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 1W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:1 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 2W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mssql' AND current_worker:2 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 2W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:2 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 2W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:2 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 4W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mssql' AND current_worker:4 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 4W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:4 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 4W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:4 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 8W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mssql' AND current_worker:8 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 8W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:8 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 8W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:8 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 16W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mssql' AND current_worker:16 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 16W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:16 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 16W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:16 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 32W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mssql' AND current_worker:32 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 32W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:32 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 32W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:32 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Hammerdb MSSQL run artifacts",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 97 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "run_artifacts_url.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "version", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mssql'",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Uperf norm ltcy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 }, "repeat": "Uperf_msg_size" },
  {
   "title": "Uperf: norm_ltcy",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 103 },
   "targets": [
    {
     "alias": "pod 64k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:1 AND kind:'pod' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 64k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:1 AND kind:'kata' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 64k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:1 AND kind:'vm' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 1024k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:1 AND kind:'pod' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 1024k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:1 AND kind:'kata' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 1024k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:1 AND kind:'vm' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 8192k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:1 AND kind:'pod' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 8192k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:1 AND kind:'kata' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 8192k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:1 AND kind:'vm' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 64 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:8 AND kind:'pod' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 64 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:8 AND kind:'kata' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 64 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:8 AND kind:'vm' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 1024k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:8 AND kind:'pod' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 1024k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:8 AND kind:'kata' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 1024k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:8 AND kind:'vm' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 8192k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:8 AND kind:'pod' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 8192k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:8 AND kind:'kata' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 8192k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:8 AND kind:'vm' AND test_type='rr'",
     "timeField": "uperf_ts"
    }
   ]
  },
  {
   "title": "Uperf: norm_ltcy (state timeline)",
   "type": "state-timeline",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 115 },
   "targets": [
    {
     "alias": "pod 64k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:1 AND kind:'pod' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 64k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:1 AND kind:'kata' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 64k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:1 AND kind:'vm' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 1024k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:1 AND kind:'pod' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 1024k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:1 AND kind:'kata' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 1024k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:1 AND kind:'vm' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 8192k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:1 AND kind:'pod' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 8192k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:1 AND kind:'kata' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 8192k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:1 AND kind:'vm' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 64k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:8 AND kind:'pod' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 64k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:8 AND kind:'kata' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 64k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:8 AND kind:'vm' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 1024k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:8 AND kind:'pod' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 1024k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:8 AND kind:'kata' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 1024 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:8 AND kind:'vm' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 8192k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:8 AND kind:'pod' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 8192k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:8 AND kind:'kata' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 8192k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:8 AND kind:'vm' AND test_type='rr'",
     "timeField": "uperf_ts"
    }
   ]
  },
  { "title": "Uperf norm byte", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 } },
  {
   "title": "Uperf: norm_byte",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 129 },
   "targets": [
    {
     "alias": "pod 64k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:1 AND kind:'pod' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 64k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:1 AND kind:'kata' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 64k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:1 AND kind:'vm' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 1024k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:1 AND kind:'pod' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 1024k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:1 AND kind:'kata' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 1024k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:1 AND kind:'vm' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 8192k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:1 AND kind:'pod' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 8192k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:1 AND kind:'kata' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 8192k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:1 AND kind:'vm' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 64 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:8 AND kind:'pod' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 64 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:8 AND kind:'kata' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 64 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:8 AND kind:'vm' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 1024k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:8 AND kind:'pod' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 1024k 8th",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:8 AND kind:'kata' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 1024k 8th",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:8 AND kind:'vm' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 8192k 8th",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:8 AND kind:'pod' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 8192k 8th",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:8 AND kind:'kata' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 8192k 8th",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:8 AND kind:'vm' AND test_type='stream'",
     "timeField": "uperf_ts"
    }
   ]
  },
  {
   "title": "Uperf: norm_byte(state timeline)",
   "type": "state-timeline",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 141 },
   "targets": [
    {
     "alias": "pod 64k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:1 AND kind:'pod' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 64k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:1 AND kind:'kata' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 64k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:1 AND kind:'vm' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 1024k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:1 AND kind:'pod' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 1024k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:1 AND kind:'kata' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 1024k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:1 AND kind:'vm' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 8192k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:1 AND kind:'pod' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 8192k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:1 AND kind:'kata' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 8192k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:1 AND kind:'vm' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 64k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:8 AND kind:'pod' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 64k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:8 AND kind:'kata' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 64k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:8 AND kind:'vm' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 1024k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:8 AND kind:'pod' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 1024k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:8 AND kind:'kata' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 1024 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:8 AND kind:'vm' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 8192k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:8 AND kind:'pod' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 8192k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:8 AND kind:'kata' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 8192k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:8 AND kind:'vm' AND test_type='stream'",
     "timeField": "uperf_ts"
    }
   ]
  },
  {
   "title": "Uperf run artifacts",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 154 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "run_artifacts_url.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "version", "id": "1", "type": "max" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Stressng CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 159 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 160 },
   "options": { "content": "## Stressng workload results" },
   "targets": [
    {
     "alias": "TPM: 1 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:1",
     "timeField": "timestamp"
    },
    {
     "alias": "TPM: 2 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Stressng: CPU",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 162 },
   "targets": [
    {
     "alias": "pod",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu", "id": "1", "type": "max" }
     ],
     "query": "kind:'pod' ",
     "timeField": "timestamp"
    },
    {
     "alias": "kata",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm'",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Stressng: CPU (state timeline)",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 173 },
   "targets": [
    {
     "alias": "pod",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu", "id": "1", "type": "max" }
     ],
     "query": "kind:'pod' ",
     "timeField": "timestamp"
    },
    {
     "alias": "kata",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "cpu",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'kata' ",
     "timeField": "timestamp"
    },
    {
     "alias": "vm",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' ",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Stressng Memcpy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 179 } },
  {
   "title": "Stressng: Memcpy",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 180 },
   "targets": [
    {
     "alias": "pod",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "memcpy", "id": "1", "type": "max" }
     ],
     "query": "kind:'pod'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "memcpy", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' ",
     "timeField": "timestamp"
    },
    {
     "alias": "vm",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "memcpy", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm'",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Stressng: Memcpy (state timeline)",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 191 },
   "targets": [
    {
     "alias": "pod",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "memcpy", "id": "1", "type": "max" }
     ],
     "query": "kind:'pod' ",
     "timeField": "timestamp"
    },
    {
     "alias": "kata",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "memcpy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'kata' ",
     "timeField": "timestamp"
    },
    {
     "alias": "vm",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "memcpy", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' ",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Stressng VM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 197 } },
  {
   "title": "Stressng: VM",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 198 },
   "targets": [
    {
     "alias": "pod",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "vm", "id": "1", "type": "max" }
     ],
     "query": "kind:'pod' ",
     "timeField": "timestamp"
    },
    {
     "alias": "kata",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "vm", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "vm", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm'",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Stressng: VM  (state timeline)",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 209 },
   "targets": [
    {
     "alias": "pod",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "vm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' ",
     "timeField": "timestamp"
    },
    {
     "alias": "kata",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "vm", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' ",
     "timeField": "timestamp"
    },
    {
     "alias": "vm",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "vm", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' ",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Stressng run artifacts",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 215 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "run_artifacts_url.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "version", "id": "1", "type": "max" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Vdbench",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 220 },
   "collapsed": true,
   "panels": [
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 }, "options": { "content": "# Workloads report " } }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 221 } },
  {
   "title": "Vdbench IOPS ",
   "type": "state-timeline",
   "gridPos": { "h": 29, "w": 24, "x": 0, "y": 222 },
   "targets": [
    {
     "alias": "pod oltp1",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Rate",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' and Run:'oltp1'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata oltp1 ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Rate", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' and Run:'oltp1'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm oltp1 ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Rate", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' and Run:'oltp1'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod oltp2  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Rate",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'oltp2'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata oltp2",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Rate", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'oltp2'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm oltp2 ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Rate", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'oltp2'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod oltphw",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Rate",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'oltphw'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata oltphw ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Rate", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'oltphw'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm oltphw  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Rate", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'oltphw'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod odss2  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Rate",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'odss2'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata odss2  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Rate", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'odss2'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm odss2  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Rate", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'odss2'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod odss128  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Rate",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'odss128'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata odss128  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Rate", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'odss128'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm odss128 ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Rate", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'odss128'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 64kb_write_2threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Rate",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'64kb_write_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 64kb_write_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Rate", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'64kb_write_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 64kb_write_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Rate", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'64kb_write_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 4kb_write_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Rate",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'4kb_write_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 4kb_write_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Rate", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'4kb_write_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 4kb_write_2threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Rate", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'4kb_write_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 64kb_cache_write_4threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Rate",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'64kb_cache_write_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 64kb_cache_write_4threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Rate", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'64kb_cache_write_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 64kb_cache_write_4threads",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Rate", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'64kb_cache_write_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 4kb_cache_read_4threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Rate",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'4kb_cache_read_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 4kb_cache_read_4threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Rate", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'4kb_cache_read_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 4kb_cache_read_4threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Rate", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'4kb_cache_read_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 64kb_cache_read_4threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Rate",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'64kb_cache_read_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 64kb_cache_read_4threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Rate", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'64kb_cache_read_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 64kb_cache_read_4threads",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Rate", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'64kb_cache_read_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 4kb_read_2threads",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Rate",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'4kb_read_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 4kb_read_2threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Rate", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'4kb_read_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 4kb_read_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Rate", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'4kb_read_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 64kb_read_2threads",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Rate",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'64kb_read_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 64kb_read_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Rate", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'64kb_read_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 64kb_read_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Rate", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'64kb_read_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 4kb_cache_write_4threads",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Rate",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'4kb_cache_write_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 4kb_cache_write_4threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Rate", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'4kb_cache_write_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 4kb_cache_write_4threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Rate", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'4kb_cache_write_4threads'",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Vdbench MiB's",
   "type": "state-timeline",
   "gridPos": { "h": 29, "w": 24, "x": 0, "y": 251 },
   "targets": [
    {
     "alias": "pod oltp1",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "MB/sec",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' and Run:'oltp1'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata oltp1 ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "MB/sec", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' and Run:'oltp1'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm oltp1 ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "MB/sec", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' and Run:'oltp1'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod oltp2  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "MB/sec",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'oltp2'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata oltp2",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "MB/sec", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'oltp2'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm oltp2 ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "MB/sec", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'oltp2'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod oltphw",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "MB/sec",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'oltphw'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata oltphw ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "MB/sec", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'oltphw'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm oltphw  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "MB/sec", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'oltphw'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod odss2  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "MB/sec",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'odss2'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata odss2  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "MB/sec", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'odss2'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm odss2  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "MB/sec", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'odss2'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod odss128  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "MB/sec",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'odss128'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata odss128  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "MB/sec", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'odss128'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm odss128 ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "MB/sec", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'odss128'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 64kb_write_2threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "MB/sec",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'64kb_write_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 64kb_write_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "MB/sec", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'64kb_write_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 64kb_write_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "MB/sec", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'64kb_write_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 4kb_write_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "MB/sec",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'4kb_write_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 4kb_write_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "MB/sec", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'4kb_write_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 4kb_write_2threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "MB/sec", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'4kb_write_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 64kb_cache_write_4threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "MB/sec",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'64kb_cache_write_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 64kb_cache_write_4threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "MB/sec", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'64kb_cache_write_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 64kb_cache_write_4threads",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "MB/sec", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'64kb_cache_write_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 4kb_cache_read_4threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "MB/sec",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'4kb_cache_read_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 4kb_cache_read_4threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "MB/sec", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'4kb_cache_read_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 4kb_cache_read_4threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "MB/sec", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'4kb_cache_read_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 64kb_cache_read_4threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "MB/sec",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'64kb_cache_read_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 64kb_cache_read_4threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "MB/sec", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'64kb_cache_read_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 64kb_cache_read_4threads",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "MB/sec", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'64kb_cache_read_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 4kb_read_2threads",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "MB/sec",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'4kb_read_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 4kb_read_2threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "MB/sec", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'4kb_read_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 4kb_read_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "MB/sec", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'4kb_read_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 64kb_read_2threads",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "MB/sec",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'64kb_read_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 64kb_read_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "MB/sec", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'64kb_read_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 64kb_read_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "MB/sec", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'64kb_read_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 4kb_cache_write_4threads",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "MB/sec",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'4kb_cache_write_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 4kb_cache_write_4threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "MB/sec", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'4kb_cache_write_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 4kb_cache_write_4threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "MB/sec", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'4kb_cache_write_4threads'",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Vdbench Read Latency (ms)",
   "type": "state-timeline",
   "gridPos": { "h": 29, "w": 24, "x": 0, "y": 280 },
   "targets": [
    {
     "alias": "pod oltp1",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read_resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' and Run:'oltp1'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata oltp1 ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "read_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' and Run:'oltp1'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm oltp1 ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "read_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' and Run:'oltp1'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod oltp2  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read_resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'oltp2'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata oltp2",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "read_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'oltp2'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm oltp2 ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "read_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'oltp2'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod oltphw",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read_resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'oltphw'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata oltphw ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "read_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'oltphw'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm oltphw  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "read_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'oltphw'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod odss2  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read_resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'odss2'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata odss2  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "read_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'odss2'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm odss2  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "read_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'odss2'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod odss128  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read_resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'odss128'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata odss128  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "read_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'odss128'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm odss128 ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "read_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'odss128'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 64kb_write_2threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read_resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'64kb_write_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 64kb_write_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "read_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'64kb_write_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 64kb_write_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "read_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'64kb_write_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 4kb_write_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read_resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'4kb_write_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 4kb_write_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "read_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'4kb_write_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 4kb_write_2threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "read_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'4kb_write_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 64kb_cache_write_4threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read_resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'64kb_cache_write_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 64kb_cache_write_4threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "read_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'64kb_cache_write_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 64kb_cache_write_4threads",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "read_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'64kb_cache_write_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 4kb_cache_read_4threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read_resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'4kb_cache_read_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 4kb_cache_read_4threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "read_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'4kb_cache_read_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 4kb_cache_read_4threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "read_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'4kb_cache_read_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 64kb_cache_read_4threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read_resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'64kb_cache_read_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 64kb_cache_read_4threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "read_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'64kb_cache_read_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 64kb_cache_read_4threads",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "read_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'64kb_cache_read_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 4kb_read_2threads",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read_resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'4kb_read_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 4kb_read_2threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "read_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'4kb_read_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 4kb_read_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "read_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'4kb_read_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 64kb_read_2threads",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read_resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'64kb_read_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 64kb_read_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "read_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'64kb_read_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 64kb_read_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "read_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'64kb_read_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 4kb_cache_write_4threads",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read_resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'4kb_cache_write_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 4kb_cache_write_4threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "read_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'4kb_cache_write_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 4kb_cache_write_4threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "read_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'4kb_cache_write_4threads'",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Vdbench Write Latency (ms)",
   "type": "state-timeline",
   "gridPos": { "h": 29, "w": 24, "x": 0, "y": 309 },
   "targets": [
    {
     "alias": "kata oltp1 ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "write_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'pod' and Run:'oltp1'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod oltp1",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "write_resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'kata' and Run:'oltp1'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm oltp1 ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "write_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' and Run:'oltp1'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod oltp2  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "write_resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'oltp2'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata oltp2",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "write_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'oltp2'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm oltp2 ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "write_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'oltp2'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod oltphw",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "write_resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'oltphw'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata oltphw ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "write_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'oltphw'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm oltphw  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "write_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'oltphw'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod odss2  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "write_resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'odss2'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata odss2  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "write_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'odss2'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm odss2  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "write_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'odss2'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod odss128  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "write_resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'odss128'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata odss128  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "write_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'odss128'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm odss128 ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "write_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'odss128'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 64kb_write_2threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "write_resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'64kb_write_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 64kb_write_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "write_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'64kb_write_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 64kb_write_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "write_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'64kb_write_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 4kb_write_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "write_resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'4kb_write_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 4kb_write_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "write_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'4kb_write_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 4kb_write_2threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "write_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'4kb_write_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 64kb_cache_write_4threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Write_resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'64kb_cache_write_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 64kb_cache_write_4threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "write_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'64kb_cache_write_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 64kb_cache_write_4threads",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "write_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'64kb_cache_write_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 4kb_cache_read_4threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "write_resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'4kb_cache_read_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 4kb_cache_read_4threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "write_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'4kb_cache_read_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 4kb_cache_read_4threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "write_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'4kb_cache_read_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 64kb_cache_read_4threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "write_resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'64kb_cache_read_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 64kb_cache_read_4threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "write_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'64kb_cache_read_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 64kb_cache_read_4threads",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "write_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'64kb_cache_read_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 4kb_read_2threads",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "write_resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'4kb_read_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 4kb_read_2threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "write_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'4kb_read_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 4kb_read_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "write_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'4kb_read_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 64kb_read_2threads",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "write_resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'64kb_read_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 64kb_read_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "write_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'64kb_read_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 64kb_read_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "write_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'64kb_read_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 4kb_cache_write_4threads",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "write_resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'4kb_cache_write_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 4kb_cache_write_4threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "write_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'4kb_cache_write_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 4kb_cache_write_4threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "write_resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'4kb_cache_write_4threads'",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Vdbench Avg Latency  (ms)",
   "type": "state-timeline",
   "gridPos": { "h": 29, "w": 24, "x": 0, "y": 338 },
   "targets": [
    {
     "alias": "kata oltp1 ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'pod' and Run:'oltp1'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod oltp1",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'kata' and Run:'oltp1'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm oltp1 ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' and Run:'oltp1'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod oltp2  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'oltp2'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata oltp2",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'oltp2'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm oltp2 ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'oltp2'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod oltphw",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'oltphw'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata oltphw ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'oltphw'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm oltphw  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'oltphw'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod odss2  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'odss2'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata odss2  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'odss2'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm odss2  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'odss2'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod odss128  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'odss128'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata odss128  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'odss128'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm odss128 ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'odss128'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 64kb_write_2threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'64kb_write_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 64kb_write_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'64kb_write_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 64kb_write_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'64kb_write_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 4kb_write_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'4kb_write_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 4kb_write_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'4kb_write_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 4kb_write_2threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'4kb_write_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 64kb_cache_write_4threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'64kb_cache_write_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 64kb_cache_write_4threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'64kb_cache_write_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 64kb_cache_write_4threads",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'64kb_cache_write_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 4kb_cache_read_4threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'4kb_cache_read_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 4kb_cache_read_4threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'4kb_cache_read_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 4kb_cache_read_4threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'4kb_cache_read_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 64kb_cache_read_4threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'64kb_cache_read_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 64kb_cache_read_4threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'64kb_cache_read_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 64kb_cache_read_4threads",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'64kb_cache_read_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 4kb_read_2threads",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'4kb_read_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 4kb_read_2threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'4kb_read_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 4kb_read_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'4kb_read_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 64kb_read_2threads",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'64kb_read_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 64kb_read_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'64kb_read_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 64kb_read_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'64kb_read_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 4kb_cache_write_4threads",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Resp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'4kb_cache_write_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 4kb_cache_write_4threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'4kb_cache_write_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 4kb_cache_write_4threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'4kb_cache_write_4threads'",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Vdbench Latency std (ms)",
   "type": "state-timeline",
   "gridPos": { "h": 29, "w": 24, "x": 0, "y": 367 },
   "targets": [
    {
     "alias": "kata oltp1 ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp_std", "id": "1", "type": "max" }
     ],
     "query": "kind:'pod' and Run:'oltp1'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod oltp1",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Resp_std",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'kata' and Run:'oltp1'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm oltp1 ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp_std", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' and Run:'oltp1'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod oltp2  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Resp_std",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'oltp2'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata oltp2",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp_std", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'oltp2'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm oltp2 ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp_std", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'oltp2'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod oltphw",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Resp_std",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'oltphw'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata oltphw ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp_std", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'oltphw'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm oltphw  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp_std", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'oltphw'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod odss2  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Resp_std",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'odss2'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata odss2  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp_std", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'odss2'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm odss2  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp_std", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'odss2'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod odss128  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Resp_std",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'odss128'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata odss128  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp_std", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'odss128'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm odss128 ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp_std", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'odss128'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 64kb_write_2threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Resp_std",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'64kb_write_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 64kb_write_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp_std", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'64kb_write_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 64kb_write_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp_std", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'64kb_write_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 4kb_write_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Resp_std",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'4kb_write_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 4kb_write_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp_std", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'4kb_write_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 4kb_write_2threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp_std", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'4kb_write_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 64kb_cache_write_4threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Resp_std",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'64kb_cache_write_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 64kb_cache_write_4threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp_std", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'64kb_cache_write_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 64kb_cache_write_4threads",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp_std", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'64kb_cache_write_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 4kb_cache_read_4threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Resp_std",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'4kb_cache_read_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 4kb_cache_read_4threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp_std", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'4kb_cache_read_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 4kb_cache_read_4threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp_std", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'4kb_cache_read_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 64kb_cache_read_4threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Resp_std",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'64kb_cache_read_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 64kb_cache_read_4threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp_std", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'64kb_cache_read_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 64kb_cache_read_4threads",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp_std", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'64kb_cache_read_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 4kb_read_2threads",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Resp_std",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'4kb_read_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 4kb_read_2threads  ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp_std", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'4kb_read_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 4kb_read_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp_std", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'4kb_read_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 64kb_read_2threads",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Resp_std",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'64kb_read_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 64kb_read_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp_std", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'64kb_read_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 64kb_read_2threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp_std", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'64kb_read_2threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 4kb_cache_write_4threads",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Resp_std",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND Run:'4kb_cache_write_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 4kb_cache_write_4threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp_std", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'4kb_cache_write_4threads'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 4kb_cache_write_4threads ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Resp_std", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' AND Run:'4kb_cache_write_4threads'",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Vdbench run artifacts",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 396 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "run_artifacts_url.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "version", "id": "1", "type": "max" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 401 },
   "options": {
    "content": "![alt text](https://github.com/redhat-performance/benchmark-runner/blob/main/media/benchmark_runner.png?raw=true \"Tooltip Text\")"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 401 },
   "options": {
    "content": "![alt text](https://www.redhat.com/cms/managed-files/Brand_Standars-Red_Hat-_color_on-black.svg?itok=wPCF1-sX \"Tooltip Text\")"
   }
  }
 ]
}