{
 "title": "benchmark-runner-report",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ci_run_date",
    "label": "ci_run_date",
    "query": "{\"find\":\"terms\",\"field\":\"ci_date.keyword\"}"
   },
   {
    "name": "uuid",
    "label": "uuid",
    "query": "{\"find\":\"terms\",\"field\":\"uuid.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "benchmark-runner report for date: $ci_run_date",
   "type": "text",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 0 },
   "options": {
    "content": "![alt text](https://github.com/redhat-performance/benchmark-runner/blob/main/media/benchmark_runner.png?raw=true \"Tooltip Text\")"
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 }, "options": { "content": "# Workloads  " } },
  { "title": "Hammerdb", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "build" },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "options": {
    "content": "## Hammerdb workload results\n![alt text](https://www.hammerdb.com/images/hammerDB-logo-FINAL.jpg \"Tooltip Text\")"
   },
   "targets": [
    {
     "alias": "TPM: 1 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:1",
     "timeField": "timestamp"
    },
    {
     "alias": "TPM: 2 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 13 },
   "options": {
    "content": "![alt text](https://github.com/redhat-performance/benchmark-runner/blob/main/media/mariadb.png?raw=true \"Tooltip Text\")"
   },
   "targets": [
    {
     "alias": "TPM: 1 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:1",
     "timeField": "timestamp"
    },
    {
     "alias": "TPM: 2 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "TPM" }
   ],
   "targets": [
    {
     "alias": "1 worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:1 AND kind:'pod' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "2 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2 AND kind:'pod' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "4 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:4 AND kind:'pod' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "8 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:8 AND kind:'pod' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "16 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:16 AND kind:'pod' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "32 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:32 AND kind:'pod' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "TPM" }
   ],
   "targets": [
    {
     "alias": "1 worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:1 AND kind:'vm' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "2 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2 AND kind:'vm' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "4 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:4 AND kind:'vm' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "8 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:8 AND kind:'vm' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "16 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:16 AND kind:'vm' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "32 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:32 AND kind:'vm' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Kata",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "TPM" }
   ],
   "targets": [
    {
     "alias": "1 worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:1 AND kind:'kata' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "2 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2 AND kind:'kata' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "4 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:4 AND kind:'kata' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "8 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:8 AND kind:'kata' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "16 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:16 AND kind:'kata' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "32 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:32 AND kind:'kata' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Hammerdb Mariadb  run artifacts",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "run_artifacts_url.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "version",
       "hide": true,
       "id": "1",
       "type": "max"
      }
     ],
     "query": "db_type='mariadb' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 49 },
   "options": {
    "content": "![alt text](https://github.com/redhat-performance/benchmark-runner/blob/main/media/postgresql.png?raw=true \"Tooltip Text\")"
   },
   "targets": [
    {
     "alias": "TPM: 1 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:1",
     "timeField": "timestamp"
    },
    {
     "alias": "TPM: 2 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short", "label": "TPM" }
   ],
   "targets": [
    {
     "alias": "1 worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:1 AND kind:'pod' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "2 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:2 AND kind:'pod' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "4 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:4 AND kind:'pod' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "8 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:8 AND kind:'pod' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "16 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:16 AND kind:'pod' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "32 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:32 AND kind:'pod' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short", "label": "TPM" }
   ],
   "targets": [
    {
     "alias": "1 worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:1 AND kind:'vm' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "2 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:2 AND kind:'vm' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "4 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:4 AND kind:'vm' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "8 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:8 AND kind:'vm' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "16 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:16 AND kind:'vm' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "32 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:32 AND kind:'vm' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Kata",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short", "label": "TPM" }
   ],
   "targets": [
    {
     "alias": "1 worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:1 AND kind:'kata' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "2 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:2 AND kind:'kata' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "4 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:4 AND kind:'kata' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "8 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:8 AND kind:'kata' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "16 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:16 AND kind:'kata' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "32 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:32 AND kind:'kata' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Hammerdb PostgreSQL  run artifacts",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "run_artifacts_url.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "version",
       "hide": true,
       "id": "1",
       "type": "max"
      }
     ],
     "query": "db_type='pg' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 85 },
   "options": {
    "content": "![alt text](https://github.com/redhat-performance/benchmark-runner/blob/main/media/mssql.png?raw=true \"Tooltip Text\")"
   },
   "targets": [
    {
     "alias": "TPM: 1 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:1",
     "timeField": "timestamp"
    },
    {
     "alias": "TPM: 2 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short", "label": "TPM" }
   ],
   "targets": [
    {
     "alias": "1 worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:1 AND kind:'pod' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "2 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:2 AND kind:'pod' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "4 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:4 AND kind:'pod' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "8 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:8 AND kind:'pod' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "16 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:16 AND kind:'pod' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "32 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:32 AND kind:'pod' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "short", "label": "TPM" }
   ],
   "targets": [
    {
     "alias": "1 worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:1 AND kind:'vm' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "2 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:2 AND kind:'vm' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "4 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:4 AND kind:'vm' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "8 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:8 AND kind:'vm' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "16 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:16 AND kind:'vm' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "32 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:32 AND kind:'vm' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Kata",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "short", "label": "TPM" }
   ],
   "targets": [
    {
     "alias": "1 worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:1 AND kind:'kata' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "2 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:2 AND kind:'kata' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "4 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:4 AND kind:'kata' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "8 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:8 AND kind:'kata' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "16 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:16 AND kind:'kata' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "32 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:32 AND kind:'kata' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Hammerdb MSSQL run artifacts",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 116 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "run_artifacts_url.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "version",
       "hide": true,
       "id": "1",
       "type": "max"
      }
     ],
     "query": "db_type='mssql' AND ci_run_date=$ci_run_date",
     "timeField": "uperf_ts"
    }
   ]
  },
  { "title": "Uperf", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 121 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 122 },
   "options": { "content": "## Uperf workload results" },
   "targets": [
    {
     "alias": "TPM: 1 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:1",
     "timeField": "timestamp"
    },
    {
     "alias": "TPM: 2 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Uperf - norm_ltcy - 1 thread",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 125 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "64 vm",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND kind:'vm' AND num_threads:1 AND ci_run_date=$ci_run_date AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "64 pod",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND kind:'pod' AND num_threads:1 AND ci_run_date=$ci_run_date AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "64 kata",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND kind:'kata' AND num_threads:1 AND ci_run_date=$ci_run_date AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "1024 vm",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND kind:'vm' AND num_threads:1 AND ci_run_date=$ci_run_date AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "1024 pod",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND kind:'pod' AND num_threads:1 AND ci_run_date=$ci_run_date AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "1024 kata",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND kind:'kata' AND num_threads:1 AND ci_run_date=$ci_run_date AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "8192 vm",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND kind:'vm' AND num_threads:1 AND ci_run_date=$ci_run_date AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "8192 pod",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND kind:'pod' AND num_threads:1 AND ci_run_date=$ci_run_date AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "8192 kata",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND kind:'kata' AND num_threads:1 AND ci_run_date=$ci_run_date AND test_type='rr'",
     "timeField": "uperf_ts"
    }
   ]
  },
  {
   "title": "Uperf - norm_ltcy - 8 threads",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "64 vm",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND kind:'vm' AND num_threads:8 AND ci_run_date=$ci_run_date AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "64 pod",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND kind:'pod' AND num_threads:8 AND ci_run_date=$ci_run_date AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "64 kata",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND kind:'kata' AND num_threads:8 AND ci_run_date=$ci_run_date AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "1024 vm",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND kind:'vm' AND num_threads:8 AND ci_run_date=$ci_run_date AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "1024 pod",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND kind:'pod' AND num_threads:8 AND ci_run_date=$ci_run_date AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "1024 kata",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND kind:'kata' AND num_threads:8 AND ci_run_date=$ci_run_date AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "8192 vm",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND kind:'vm' AND num_threads:8 AND ci_run_date=$ci_run_date AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "8192 pod",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND kind:'pod' AND num_threads:8 AND ci_run_date=$ci_run_date AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "8192 kata",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND kind:'kata' AND num_threads:8 AND ci_run_date=$ci_run_date AND test_type='rr'",
     "timeField": "uperf_ts"
    }
   ]
  },
  {
   "title": "Uperf - norm_byte - 1 thread",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 147 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "64 vm",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND kind:'vm' AND num_threads:1 AND ci_run_date=$ci_run_date AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "64 pod",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND kind:'pod' AND num_threads:1 AND ci_run_date=$ci_run_date AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "64 kata",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND kind:'kata' AND num_threads:1 AND ci_run_date=$ci_run_date AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "1024 vm",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND kind:'vm' AND num_threads:1 AND ci_run_date=$ci_run_date AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "1024 pod",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND kind:'pod' AND num_threads:1 AND ci_run_date=$ci_run_date AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "1024 kata",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND kind:'kata' AND num_threads:1 AND ci_run_date=$ci_run_date AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "8192 vm",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND kind:'vm' AND num_threads:1 AND ci_run_date=$ci_run_date AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "8192 pod",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND kind:'pod' AND num_threads:1 AND ci_run_date=$ci_run_date AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "8192 kata",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND kind:'kata' AND num_threads:1 AND ci_run_date=$ci_run_date AND test_type='stream'",
     "timeField": "uperf_ts"
    }
   ]
  },
  {
   "title": "Uperf - norm_byte - 8 threads",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 158 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "64 vm",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND kind:'vm' AND num_threads:8 AND ci_run_date=$ci_run_date AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "64 pod",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND kind:'pod' AND num_threads:8 AND ci_run_date=$ci_run_date AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "64 kata",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND kind:'kata' AND num_threads:8 AND ci_run_date=$ci_run_date AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "1024 vm",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND kind:'vm' AND num_threads:8 AND ci_run_date=$ci_run_date AND test_type='stream' ",
     "timeField": "uperf_ts"
    },
    {
     "alias": "1024 pod",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND kind:'pod' AND num_threads:8 AND ci_run_date=$ci_run_date AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "1024 kata",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND kind:'kata' AND num_threads:8 AND ci_run_date=$ci_run_date AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "8192 vm",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND kind:'vm' AND num_threads:8 AND ci_run_date=$ci_run_date AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "8192 pod",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND kind:'pod' AND num_threads:8 AND ci_run_date=$ci_run_date AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "8192 kata",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND kind:'kata' AND num_threads:8 AND ci_run_date=$ci_run_date AND test_type='stream'",
     "timeField": "uperf_ts"
    }
   ]
  },
  {
   "title": "Uperf run artifacts",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 169 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "run_artifacts_url.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "version",
       "hide": true,
       "id": "1",
       "type": "max"
      }
     ],
     "query": "ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Stressng", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 174 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 175 },
   "options": { "content": "## Stressng workload results" },
   "targets": [
    {
     "alias": "TPM: 1 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:1",
     "timeField": "timestamp"
    },
    {
     "alias": "TPM: 2 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Stressng CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 177 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "CPU VM",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "cpu",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'vm' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "CPU Pod",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "cpu",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "CPU Kata",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "cpu",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'kata' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Stressng Memcpy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 185 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Memcpy VM",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "memcpy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'vm' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "Memcpy Pod",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "memcpy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "Memcpy Kata",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "memcpy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'kata' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Stressng Vm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 193 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Memcpy VM",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "vm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'vm' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "Memcpy Pod",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "vm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    },
    {
     "alias": "Memcpy Kata",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "vm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'kata' AND ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Stressng run artifacts",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 201 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "run_artifacts_url.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "version",
       "hide": true,
       "id": "1",
       "type": "max"
      }
     ],
     "query": "ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Vdbench", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 206 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 207 },
   "options": { "content": "## Vdbench workload results" },
   "targets": [
    {
     "alias": "TPM: 1 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:1",
     "timeField": "timestamp"
    },
    {
     "alias": "TPM: 2 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Vdbench pod: oltp1",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 209 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu_kernel", "id": "1", "type": "max" },
      { "field": "cpu_used", "id": "3", "type": "max" },
      { "field": "cpu_user", "id": "4", "type": "max" },
      { "field": "MB_write", "id": "5", "type": "max" },
      { "field": "Write_resp_max", "id": "9", "type": "max" },
      { "field": "Read_rate", "id": "10", "type": "max" },
      { "field": "Read_rate_max", "id": "12", "type": "max" },
      { "field": "Read_rate_std", "id": "13", "type": "max" },
      { "field": "MB_read", "id": "14", "type": "max" }
     ],
     "query": "kind:'pod' AND Run:'oltp1' AND ci_date:$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Vdbench pod: oltp2",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 219 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu_kernel", "id": "1", "type": "max" },
      { "field": "cpu_used", "id": "3", "type": "max" },
      { "field": "cpu_user", "id": "4", "type": "max" },
      { "field": "MB_write", "id": "5", "type": "max" },
      { "field": "Write_resp_max", "id": "9", "type": "max" },
      { "field": "Read_rate", "id": "10", "type": "max" },
      { "field": "Read_rate_max", "id": "12", "type": "max" },
      { "field": "Read_rate_std", "id": "13", "type": "max" },
      { "field": "MB_read", "id": "14", "type": "max" }
     ],
     "query": "kind:'pod' AND Run:'oltp2' AND ci_date:$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Vdbench pod: odss128",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 229 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu_kernel", "id": "1", "type": "max" },
      { "field": "cpu_used", "id": "3", "type": "max" },
      { "field": "cpu_user", "id": "4", "type": "max" },
      { "field": "MB_write", "id": "5", "type": "max" },
      { "field": "Write_resp_max", "id": "9", "type": "max" },
      { "field": "Read_rate", "id": "10", "type": "max" },
      { "field": "Read_rate_max", "id": "12", "type": "max" },
      { "field": "Read_rate_std", "id": "13", "type": "max" },
      { "field": "MB_read", "id": "14", "type": "max" }
     ],
     "query": "kind:'pod' AND Run:'odss128' AND ci_date:$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Vdbench pod: odss2",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 239 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu_kernel", "id": "1", "type": "max" },
      { "field": "cpu_used", "id": "3", "type": "max" },
      { "field": "cpu_user", "id": "4", "type": "max" },
      { "field": "MB_write", "id": "5", "type": "max" },
      { "field": "Write_resp_max", "id": "9", "type": "max" },
      { "field": "Read_rate", "id": "10", "type": "max" },
      { "field": "Read_rate_max", "id": "12", "type": "max" },
      { "field": "Read_rate_std", "id": "13", "type": "max" },
      { "field": "MB_read", "id": "14", "type": "max" }
     ],
     "query": "kind:'pod' AND Run:'odss2' AND ci_date:$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Vdbench pod: oltphw",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 249 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu_kernel", "id": "1", "type": "max" },
      { "field": "cpu_used", "id": "3", "type": "max" },
      { "field": "cpu_user", "id": "4", "type": "max" },
      { "field": "MB_write", "id": "5", "type": "max" },
      { "field": "Write_resp_max", "id": "9", "type": "max" },
      { "field": "Read_rate", "id": "10", "type": "max" },
      { "field": "Read_rate_max", "id": "12", "type": "max" },
      { "field": "Read_rate_std", "id": "13", "type": "max" },
      { "field": "MB_read", "id": "14", "type": "max" }
     ],
     "query": "kind:'pod' AND Run:'oltphw' AND ci_date:$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Vdbench pod: 4kb_read_2threads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 259 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu_kernel", "id": "1", "type": "max" },
      { "field": "cpu_used", "id": "3", "type": "max" },
      { "field": "cpu_user", "id": "4", "type": "max" },
      { "field": "MB_write", "id": "5", "type": "max" },
      { "field": "Write_resp_max", "id": "9", "type": "max" },
      { "field": "Read_rate", "id": "10", "type": "max" },
      { "field": "Read_rate_max", "id": "12", "type": "max" },
      { "field": "Read_rate_std", "id": "13", "type": "max" },
      { "field": "MB_read", "id": "14", "type": "max" }
     ],
     "query": "kind:'pod' AND Run:'4kb_read_2threads' AND ci_date:$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Vdbench pod: 4kb_write_2threads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 269 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu_kernel", "id": "1", "type": "max" },
      { "field": "cpu_used", "id": "3", "type": "max" },
      { "field": "cpu_user", "id": "4", "type": "max" },
      { "field": "MB_write", "id": "5", "type": "max" },
      { "field": "Write_resp_max", "id": "9", "type": "max" },
      { "field": "Read_rate", "id": "10", "type": "max" },
      { "field": "Read_rate_max", "id": "12", "type": "max" },
      { "field": "Read_rate_std", "id": "13", "type": "max" },
      { "field": "MB_read", "id": "14", "type": "max" }
     ],
     "query": "kind:'pod' AND Run:'4kb_write_2threads' AND ci_date:$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Vdbench pod: 4kb_cache_read_4threads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 279 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu_kernel", "id": "1", "type": "max" },
      { "field": "cpu_used", "id": "3", "type": "max" },
      { "field": "cpu_user", "id": "4", "type": "max" },
      { "field": "MB_write", "id": "5", "type": "max" },
      { "field": "Write_resp_max", "id": "9", "type": "max" },
      { "field": "Read_rate", "id": "10", "type": "max" },
      { "field": "Read_rate_max", "id": "12", "type": "max" },
      { "field": "Read_rate_std", "id": "13", "type": "max" },
      { "field": "MB_read", "id": "14", "type": "max" }
     ],
     "query": "kind:'pod' AND Run:'4kb_cache_read_4threads' AND ci_date:$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Vdbench pod: 4kb_cache_write_4threads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 289 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu_kernel", "id": "1", "type": "max" },
      { "field": "cpu_used", "id": "3", "type": "max" },
      { "field": "cpu_user", "id": "4", "type": "max" },
      { "field": "MB_write", "id": "5", "type": "max" },
      { "field": "Write_resp_max", "id": "9", "type": "max" },
      { "field": "Write_resp_std", "id": "10", "type": "max" }
     ],
     "query": "kind:'pod' AND Run:'4kb_cache_write_4threads' AND ci_date:$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Vdbench pod: 64kb_read_2threads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 299 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu_kernel", "id": "1", "type": "max" },
      { "field": "cpu_used", "id": "3", "type": "max" },
      { "field": "cpu_user", "id": "4", "type": "max" },
      { "field": "MB_write", "id": "5", "type": "max" },
      { "field": "Write_resp_max", "id": "9", "type": "max" },
      { "field": "Read_rate", "id": "10", "type": "max" },
      { "field": "Read_rate_max", "id": "12", "type": "max" },
      { "field": "Read_rate_std", "id": "13", "type": "max" },
      { "field": "MB_read", "id": "14", "type": "max" }
     ],
     "query": "kind:'pod' AND Run:64kb_read_2threads' AND ci_date:$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Vdbench pod: 64kb_write_2threads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 309 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu_kernel", "id": "1", "type": "max" },
      { "field": "cpu_used", "id": "3", "type": "max" },
      { "field": "cpu_user", "id": "4", "type": "max" },
      { "field": "MB_write", "id": "5", "type": "max" },
      { "field": "Write_resp_max", "id": "9", "type": "max" },
      { "field": "Read_rate", "id": "10", "type": "max" },
      { "field": "Read_rate_max", "id": "12", "type": "max" },
      { "field": "Read_rate_std", "id": "13", "type": "max" },
      { "field": "MB_read", "id": "14", "type": "max" }
     ],
     "query": "kind:'pod' AND Run:'64kb_write_2threads' AND ci_date:$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Vdbench pod: 64kb_cache_read_4threads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 319 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu_kernel", "id": "1", "type": "max" },
      { "field": "cpu_used", "id": "3", "type": "max" },
      { "field": "cpu_user", "id": "4", "type": "max" },
      { "field": "MB_write", "id": "5", "type": "max" },
      { "field": "Write_resp_max", "id": "9", "type": "max" },
      { "field": "Read_rate", "id": "10", "type": "max" },
      { "field": "Read_rate_max", "id": "12", "type": "max" },
      { "field": "Read_rate_std", "id": "13", "type": "max" },
      { "field": "MB_read", "id": "14", "type": "max" }
     ],
     "query": "kind:'pod' AND Run:'64kb_cache_read_4threads' AND ci_date:$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Vdbench pod: 64kb_cache_write_4threads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 329 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu_kernel", "id": "1", "type": "max" },
      { "field": "cpu_used", "id": "3", "type": "max" },
      { "field": "cpu_user", "id": "4", "type": "max" },
      { "field": "MB_write", "id": "5", "type": "max" },
      { "field": "Write_resp_max", "id": "9", "type": "max" },
      { "field": "Read_rate", "id": "10", "type": "max" },
      { "field": "Read_rate_max", "id": "12", "type": "max" },
      { "field": "Read_rate_std", "id": "13", "type": "max" },
      { "field": "MB_read", "id": "14", "type": "max" }
     ],
     "query": "kind:'pod' AND Run:'64kb_cache_write_4threads' AND ci_date:$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Vdbench pod: fillup",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 339 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu_kernel", "id": "1", "type": "max" },
      { "field": "cpu_used", "id": "3", "type": "max" },
      { "field": "cpu_user", "id": "4", "type": "max" },
      { "field": "MB_write", "id": "5", "type": "max" },
      { "field": "Write_resp_max", "id": "9", "type": "max" },
      { "field": "Read_rate", "id": "10", "type": "max" },
      { "field": "Read_rate_max", "id": "12", "type": "max" },
      { "field": "Read_rate_std", "id": "13", "type": "max" },
      { "field": "MB_read", "id": "14", "type": "max" }
     ],
     "query": "kind:'pod' AND Run:'fillup' AND ci_date:$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Vdbench kata: oltp1",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 349 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu_kernel", "id": "1", "type": "max" },
      { "field": "cpu_used", "id": "3", "type": "max" },
      { "field": "cpu_user", "id": "4", "type": "max" },
      { "field": "MB_write", "id": "5", "type": "max" },
      { "field": "Write_resp_max", "id": "9", "type": "max" },
      { "field": "Read_rate", "id": "10", "type": "max" },
      { "field": "Read_rate_max", "id": "12", "type": "max" },
      { "field": "Read_rate_std", "id": "13", "type": "max" },
      { "field": "MB_read", "id": "14", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'oltp1' AND ci_date:$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Vdbench kata: oltp2",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 359 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu_kernel", "id": "1", "type": "max" },
      { "field": "cpu_used", "id": "3", "type": "max" },
      { "field": "cpu_user", "id": "4", "type": "max" },
      { "field": "MB_write", "id": "5", "type": "max" },
      { "field": "Write_resp_max", "id": "9", "type": "max" },
      { "field": "Read_rate", "id": "10", "type": "max" },
      { "field": "Read_rate_max", "id": "12", "type": "max" },
      { "field": "Read_rate_std", "id": "13", "type": "max" },
      { "field": "MB_read", "id": "14", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'oltp2' AND ci_date:$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Vdbench kata: odss128",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 369 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu_kernel", "id": "1", "type": "max" },
      { "field": "cpu_used", "id": "3", "type": "max" },
      { "field": "cpu_user", "id": "4", "type": "max" },
      { "field": "MB_write", "id": "5", "type": "max" },
      { "field": "Write_resp_max", "id": "9", "type": "max" },
      { "field": "Read_rate", "id": "10", "type": "max" },
      { "field": "Read_rate_max", "id": "12", "type": "max" },
      { "field": "Read_rate_std", "id": "13", "type": "max" },
      { "field": "MB_read", "id": "14", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'odss128' AND ci_date:$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Vdbench kata: odss2",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 379 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu_kernel", "id": "1", "type": "max" },
      { "field": "cpu_used", "id": "3", "type": "max" },
      { "field": "cpu_user", "id": "4", "type": "max" },
      { "field": "MB_write", "id": "5", "type": "max" },
      { "field": "Write_resp_max", "id": "9", "type": "max" },
      { "field": "Read_rate", "id": "10", "type": "max" },
      { "field": "Read_rate_max", "id": "12", "type": "max" },
      { "field": "Read_rate_std", "id": "13", "type": "max" },
      { "field": "MB_read", "id": "14", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'odss2' AND ci_date:$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Vdbench kata: oltphw",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 389 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu_kernel", "id": "1", "type": "max" },
      { "field": "cpu_used", "id": "3", "type": "max" },
      { "field": "cpu_user", "id": "4", "type": "max" },
      { "field": "MB_write", "id": "5", "type": "max" },
      { "field": "Write_resp_max", "id": "9", "type": "max" },
      { "field": "Read_rate", "id": "10", "type": "max" },
      { "field": "Read_rate_max", "id": "12", "type": "max" },
      { "field": "Read_rate_std", "id": "13", "type": "max" },
      { "field": "MB_read", "id": "14", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'oltphw' AND ci_date:$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Vdbench kata: 4kb_read_2threads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 399 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu_kernel", "id": "1", "type": "max" },
      { "field": "cpu_used", "id": "3", "type": "max" },
      { "field": "cpu_user", "id": "4", "type": "max" },
      { "field": "MB_write", "id": "5", "type": "max" },
      { "field": "Write_resp_max", "id": "9", "type": "max" },
      { "field": "Read_rate", "id": "10", "type": "max" },
      { "field": "Read_rate_max", "id": "12", "type": "max" },
      { "field": "Read_rate_std", "id": "13", "type": "max" },
      { "field": "MB_read", "id": "14", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'4kb_read_2threads' AND ci_date:$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Vdbench kata: 4kb_write_2threads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 409 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu_kernel", "id": "1", "type": "max" },
      { "field": "cpu_used", "id": "3", "type": "max" },
      { "field": "cpu_user", "id": "4", "type": "max" },
      { "field": "MB_write", "id": "5", "type": "max" },
      { "field": "Write_resp_max", "id": "9", "type": "max" },
      { "field": "Read_rate", "id": "10", "type": "max" },
      { "field": "Read_rate_max", "id": "12", "type": "max" },
      { "field": "Read_rate_std", "id": "13", "type": "max" },
      { "field": "MB_read", "id": "14", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'4kb_write_2threads' AND ci_date:$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Vdbench kata: 4kb_cache_read_4threads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 419 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu_kernel", "id": "1", "type": "max" },
      { "field": "cpu_used", "id": "3", "type": "max" },
      { "field": "cpu_user", "id": "4", "type": "max" },
      { "field": "MB_write", "id": "5", "type": "max" },
      { "field": "Write_resp_max", "id": "9", "type": "max" },
      { "field": "Read_rate", "id": "10", "type": "max" },
      { "field": "Read_rate_max", "id": "12", "type": "max" },
      { "field": "Read_rate_std", "id": "13", "type": "max" },
      { "field": "MB_read", "id": "14", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'4kb_cache_read_4threads' AND ci_date:$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Vdbench kata: 64kb_cache_write_4threads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 429 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu_kernel", "id": "1", "type": "max" },
      { "field": "cpu_used", "id": "3", "type": "max" },
      { "field": "cpu_user", "id": "4", "type": "max" },
      { "field": "MB_write", "id": "5", "type": "max" },
      { "field": "Write_resp_max", "id": "9", "type": "max" },
      { "field": "Read_rate", "id": "10", "type": "max" },
      { "field": "Read_rate_max", "id": "12", "type": "max" },
      { "field": "Read_rate_std", "id": "13", "type": "max" },
      { "field": "MB_read", "id": "14", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'64kb_cache_write_4threads' AND ci_date:$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Vdbench kata: 64kb_read_2threads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 439 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu_kernel", "id": "1", "type": "max" },
      { "field": "cpu_used", "id": "3", "type": "max" },
      { "field": "cpu_user", "id": "4", "type": "max" },
      { "field": "MB_write", "id": "5", "type": "max" },
      { "field": "Write_resp_max", "id": "9", "type": "max" },
      { "field": "Read_rate", "id": "10", "type": "max" },
      { "field": "Read_rate_max", "id": "12", "type": "max" },
      { "field": "Read_rate_std", "id": "13", "type": "max" },
      { "field": "MB_read", "id": "14", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:64kb_read_2threads' AND ci_date:$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Vdbench kata: 64kb_write_2threads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 449 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu_kernel", "id": "1", "type": "max" },
      { "field": "cpu_used", "id": "3", "type": "max" },
      { "field": "cpu_user", "id": "4", "type": "max" },
      { "field": "MB_write", "id": "5", "type": "max" },
      { "field": "Write_resp_max", "id": "9", "type": "max" },
      { "field": "Read_rate", "id": "10", "type": "max" },
      { "field": "Read_rate_max", "id": "12", "type": "max" },
      { "field": "Read_rate_std", "id": "13", "type": "max" },
      { "field": "MB_read", "id": "14", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'64kb_write_2threads' AND ci_date:$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Vdbench kata: 64kb_cache_read_4threads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 459 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu_kernel", "id": "1", "type": "max" },
      { "field": "cpu_used", "id": "3", "type": "max" },
      { "field": "cpu_user", "id": "4", "type": "max" },
      { "field": "MB_write", "id": "5", "type": "max" },
      { "field": "Write_resp_max", "id": "9", "type": "max" },
      { "field": "Read_rate", "id": "10", "type": "max" },
      { "field": "Read_rate_max", "id": "12", "type": "max" },
      { "field": "Read_rate_std", "id": "13", "type": "max" },
      { "field": "MB_read", "id": "14", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'64kb_cache_read_4threads' AND ci_date:$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Vdbench kata: 4kb_cache_write_4threads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 469 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu_kernel", "id": "1", "type": "max" },
      { "field": "cpu_used", "id": "3", "type": "max" },
      { "field": "cpu_user", "id": "4", "type": "max" },
      { "field": "MB_write", "id": "5", "type": "max" },
      { "field": "Write_resp_max", "id": "9", "type": "max" },
      { "field": "Write_resp_std", "id": "10", "type": "max" }
     ],
     "query": "kind:'kata' AND Run:'4kb_cache_write_4threads' AND ci_date:$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Vdbench run artifacts",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 479 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "run_artifacts_url.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "version",
       "hide": true,
       "id": "1",
       "type": "max"
      }
     ],
     "query": "ci_run_date=$ci_run_date",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 484 },
   "options": {
    "content": "![alt text](https://www.redhat.com/cms/managed-files/Brand_Standars-Red_Hat-_color_on-black.svg?itok=wPCF1-sX \"Tooltip Text\")"
   }
  }
 ]
}