{
 "title": "regression-summary",
 "time": { "from": "now-45d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ocp_version",
    "label": "ocp_version",
    "query": "{\"find\":\"terms\",\"field\":\"ocp_version.keyword\"}"
   },
   {
    "name": "db_type",
    "query": "{\"find\":\"terms\",\"field\":\"db_type.keyword\"}"
   },
   {
    "name": "current_worker",
    "query": "{\"find\":\"terms\",\"field\":\"current_worker\"}"
   },
   {
    "name": "kind",
    "query": "{\"find\":\"terms\",\"field\":\"kind.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "perf CI state timeline color scheme",
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "<pre>\nPeak for each row  => Blue\n90% - 100% of peak => Green\n80% -  90% of peak => Light Green\n50% -  80% of peak => Orange\n 0% -  50% of peak => Red\n</pre>\n           "
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Product Version Numbers",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "alias": "ocp_version",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "settings": {
        "script": "Integer.parseInt(\"0\"+doc['ocp_version.keyword'].value.replace(\".\",\"\").replace(\"r\",\"\").replace(\"c\",\"\").replace(\"f\",\"\").replace(\"-\",\"\"))"
       },
       "type": "max"
      }
     ],
     "query": "_exists_:ocp_version",
     "timeField": "timestamp"
    },
    {
     "alias": "ocs_version",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "settings": {
        "script": "Integer.parseInt(\"0\"+doc['ocs_version.keyword'].value.replace(\".\",\"\").replace(\"r\",\"\").replace(\"c\",\"\").replace(\"f\",\"\").replace(\"-\",\"\"))"
       },
       "type": "max"
      }
     ],
     "query": "_exists_:ocs_version",
     "timeField": "timestamp"
    },
    {
     "alias": "odf_version",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "settings": {
        "script": "Integer.parseInt(\"0\"+doc['odf_version.keyword'].value.replace(\".\",\"\").replace(\"r\",\"\").replace(\"c\",\"\").replace(\"f\",\"\").replace(\"-\",\"\"))"
       },
       "type": "max"
      }
     ],
     "query": "_exists_:odf_version",
     "timeField": "timestamp"
    },
    {
     "alias": "cnv_version",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "settings": {
        "script": "Integer.parseInt(\"0\"+doc['cnv_version.keyword'].value.replace(\".\",\"\").replace(\"r\",\"\").replace(\"c\",\"\").replace(\"f\",\"\").replace(\"-\",\"\"))"
       },
       "type": "max"
      }
     ],
     "query": "_exists_:cnv_version",
     "timeField": "timestamp"
    },
    {
     "alias": "kata_version",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "settings": {
        "script": "Integer.parseInt(doc['kata_version.keyword'].value.replace(\".\",\"\"))"
       },
       "type": "max"
      }
     ],
     "query": "_exists_:kata_version",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "HammerDB KTPM (by db type, workers, and pod/vm/kata))",
   "type": "state-timeline",
   "gridPos": { "h": 28, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "db_type.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "current_worker",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "kind.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "settings": { "script": "_value/1000" }, "type": "max" }
     ],
     "query": "_exists_:tpm AND db_type:$db_type AND current_worker:$current_worker AND kind:$kind",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Uperf Gbits/s (by message size, threads, and pod/kata/VM)",
   "type": "state-timeline",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "read_message_size",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "num_threads",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "kind.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "uperf_ts",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "settings": { "script": "_value*8/1000000000" }, "type": "avg" }
     ],
     "query": "_exists_:norm_ops AND read_message_size:(64 OR 1024 OR 8192) AND num_threads:(1 OR 8) AND test_type:stream",
     "timeField": "uperf_ts"
    }
   ]
  },
  {
   "title": "Uperf latency (usecs) (by message size, threads, and pod/kata/VM)",
   "type": "state-timeline",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "read_message_size",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "num_threads",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "kind.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "uperf_ts",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "norm_ltcy",
       "id": "1",
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "_exists_:norm_ltcy AND read_message_size:(64 OR 1024 OR 8192) AND num_threads:(1) AND test_type:rr AND norm_ltcy:<1000",
     "timeField": "uperf_ts"
    },
    {
     "bucketAggs": [
      {
       "field": "read_message_size",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "num_threads",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "kind.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "settings": { "script": "_value*8" }, "type": "avg" }
     ],
     "query": "_exists_:norm_ltcy AND read_message_size:(64 OR 1024 OR 8192) AND num_threads:(8) AND test_type:rr AND norm_ltcy:<1000",
     "timeField": "uperf_ts"
    }
   ]
  },
  {
   "title": "stressng cpu bogo ops (millions) [Note: result scale changed on March 11th]",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "kind.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "cpu", "id": "1", "settings": { "script": "_value/1000000" }, "type": "max" }
     ],
     "query": "timestamp:<1646928000000",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "kind.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "cpu", "id": "1", "settings": { "script": "_value/1000000" }, "type": "max" }
     ],
     "query": "timestamp:>1646928000000",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "stressng vm bogo ops (millions) [Note: result scale changed on March 11th]",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "kind.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "vm", "id": "1", "settings": { "script": "_value/1000000" }, "type": "max" }
     ],
     "query": "timestamp:<1646928000000",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "kind.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "vm", "id": "1", "settings": { "script": "_value/1000000" }, "type": "max" }
     ],
     "query": "timestamp:>1646928000000",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "stressng memcpy bogo ops (thousands) [Note: result scale changed on March 11th]",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "kind.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "memcpy", "id": "1", "settings": { "script": "_value/1000" }, "type": "max" }
     ],
     "query": "timestamp:<1646928000000",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "kind.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "memcpy", "id": "1", "settings": { "script": "_value/1000" }, "type": "max" }
     ],
     "query": "timestamp:>1646928000000",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}