{
 "title": "benchmark-runner-ci-status-report",
 "time": { "from": "now-45d", "to": "now" },
 "panels": [
  {
   "title": "perf CI state timeline color scheme",
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "<pre>\nPeak for each row  => Blue\n90% - 100% of peak => Green\n80% -  90% of peak => Light Green\n50% -  80% of peak => Orange\n 0% -  50% of peak => Red\n</pre>\n           "
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ClusterBuster Metadata",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ClusterBuster cpusoaker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "cluster-buster-cpusoaker (Iteration/Sec)",
     "type": "state-timeline",
     "gridPos": { "h": 72, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "test_description.pods",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "test_description.name.keyword",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "4",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "iterations_sec", "id": "1", "settings": { "script": "_value/1000000" }, "type": "avg" }
       ],
       "query": "*",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "cluster-buster-cpusoaker (Iteration/CPU Sec)",
     "type": "state-timeline",
     "gridPos": { "h": 78, "w": 24, "x": 0, "y": 86 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "test_description.pods",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "test_description.name.keyword",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "4",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "iterations_cpu_sec", "id": "1", "settings": { "script": "_value/1000000" }, "type": "avg" }
       ],
       "query": "*",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "cluster-buster-cpusoaker (Memory [GB])",
     "type": "state-timeline",
     "gridPos": { "h": 77, "w": 24, "x": 0, "y": 164 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "test_description.pods",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "test_description.name.keyword",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "4",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "memory", "id": "1", "settings": { "script": "_value/1000000" }, "type": "avg" }
       ],
       "query": "*",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "ClusterBuster files",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "cluster-buster-file (Read Throughput)",
     "type": "state-timeline",
     "gridPos": { "h": 53, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "test_description.pods",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "test_description.name.keyword",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "4",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "read.io_throughput", "id": "1", "settings": { "script": "_value/1000000" }, "type": "avg" }
       ],
       "query": "*",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "ClusterBuster fio",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "cluster-buster-fio (IOPS)",
     "type": "state-timeline",
     "gridPos": { "h": 91, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "test_description.pods",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "test_description.name.keyword",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "4",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "total.iops", "id": "1", "type": "avg" }
       ],
       "query": "*",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "cluster-buster-fio (Throughput)",
     "type": "state-timeline",
     "gridPos": { "h": 116, "w": 24, "x": 0, "y": 99 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "test_description.pods",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "test_description.name.keyword",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "4",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "total.throughput", "id": "1", "settings": { "script": "_value/1000000" }, "type": "avg" }
       ],
       "query": "*",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "ClusterBuster uperf",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "cluster-buster-uperf (IOPS)",
     "type": "state-timeline",
     "gridPos": { "h": 53, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "test_description.pods",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "test_description.name.keyword",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "4",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "ops_sec", "id": "1", "settings": { "script": "_value/1000000" }, "type": "avg" }
       ],
       "query": "*",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "cluster-buster-uperf (Throughput)",
     "type": "state-timeline",
     "gridPos": { "h": 53, "w": 24, "x": 0, "y": 70 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "test_description.pods",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "test_description.name.keyword",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "4",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "rate", "id": "1", "settings": { "script": "_value/1000000" }, "type": "avg" }
       ],
       "query": "*",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Vdbench",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "vdbench average IOPS ",
     "type": "state-timeline",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "alias": " {{term Run.keyword}} :{{term kind.keyword}}",
       "bucketAggs": [
        {
         "field": "Run.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "Rate", "id": "1", "type": "max" }
       ],
       "query": "!SCALE AND !Run.keyword='fillup'",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "vdbench average IOPS  [SCALE]",
     "type": "state-timeline",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "alias": " {{term Run.keyword}} :{{term kind.keyword}}: scale  {{term scale}} ",
       "bucketAggs": [
        {
         "field": "Run.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "scale",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "Rate", "id": "1", "type": "avg" }
       ],
       "query": "SCALE AND !Run.keyword='fillup'",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  }
 ]
}