{
 "title": "benchmark-runner-summary-line-report-final",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ocp_version",
    "label": "ocp_version",
    "query": "{\"find\":\"terms\",\"field\":\"ocp_version.keyword\"}"
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# Workloads report " } },
  { "title": "Hammerdb Mariadb", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }, "repeat": "Hammerdb_workers" },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
   "options": {
    "content": "![alt text](https://github.com/redhat-performance/benchmark-runner/blob/main/media/mariadb.png?raw=true \"Tooltip Text\")"
   }
  },
  {
   "title": "Mariadb TPM ",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "pod 1W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mariadb' AND current_worker:1 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 1W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:1 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 1W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:1 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 2W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mariadb' AND current_worker:2 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 2W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 2W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 4W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mariadb' AND current_worker:4 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 4W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:4 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 4W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:4 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 8W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mariadb' AND current_worker:8 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 8W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:8 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 8W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:8 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 16W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mariadb' AND current_worker:16 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 16W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:16 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 16W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:16 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 32W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mariadb' AND current_worker:32 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 32W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:32 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 32W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:32 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Mariadb (state timeline)",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "alias": "pod 1W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mariadb' AND current_worker:1 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 1W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:1 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 1W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:1 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 2W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mariadb' AND current_worker:2 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 2W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 2W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 4W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mariadb' AND current_worker:4 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 4W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:4 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 4W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:4 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 8W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mariadb' AND current_worker:8 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 8W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:8 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 8W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:8 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 16W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mariadb' AND current_worker:16 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 16W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:16 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 16W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:16 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 32W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mariadb' AND current_worker:32 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 32W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:32 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 32W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:32 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Hammerdb mariaDB run artifacts",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "run_artifacts_url.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "version", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mariadb'",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Hammerdb PostgresSQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }, "repeat": "Hammerdb_workers" },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "options": {
    "content": "![alt text](https://github.com/redhat-performance/benchmark-runner/blob/main/media/postgresql.png?raw=true \"Tooltip Text\")"
   }
  },
  {
   "title": "PostgresSQL TPM",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "alias": "pod 1W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'pg' AND current_worker:1 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 1W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:1 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 1W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:1 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 2W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'pg' AND current_worker:2 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 2W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:2 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 2W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:2 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 4W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'pg' AND current_worker:4 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 4W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:4 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 4W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:4 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 8W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'pg' AND current_worker:8 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 8W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:8 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 8W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:8 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 16W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'pg' AND current_worker:16 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 16W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:16 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 16W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:16 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 32W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'pg' AND current_worker:32 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 32W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:32 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 32W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:32 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "PostgresSQL (state timeline)",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "alias": "pod 1W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'pg' AND current_worker:1 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 1W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:1 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 1W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:1 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 2W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'pg' AND current_worker:2 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 2W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:2 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 2W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:2 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 4W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'pg' AND current_worker:4 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 4W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:4 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 4W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:4 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 8W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'pg' AND current_worker:8 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 8W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:8 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 8W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:8 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 16W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'pg' AND current_worker:16 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 16W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:16 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 16W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:16 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 32W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'pg' AND current_worker:32 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 32W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:32 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 32W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:32 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Hammerdb PostgreSQL run artifacts",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "run_artifacts_url.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "version", "id": "1", "type": "max" }
     ],
     "query": "db_type:'pg'",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Hammerdb MSSQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 }, "repeat": "Hammerdb_workers" },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 70 },
   "options": {
    "content": "![alt text](https://github.com/redhat-performance/benchmark-runner/blob/main/media/mssql.png?raw=true \"Tooltip Text\")"
   }
  },
  {
   "title": "MSSQL TPM",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {
     "alias": "pod 1W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mssql' AND current_worker:1 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 1W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:1 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 1W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:1 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 2W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mssql' AND current_worker:2 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 2W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:2 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 2W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:2 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 4W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mssql' AND current_worker:4 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 4W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:4 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 4W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:4 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 8W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mssql' AND current_worker:8 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 8W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:8 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 8W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:8 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 16W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mssql' AND current_worker:16 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 16W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:16 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 16W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:16 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 32W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mssql' AND current_worker:32 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 32W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:32 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 32W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:32 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "MSSQL (state timeline)",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {
     "alias": "pod 1W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mssql' AND current_worker:1 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 1W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:1 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 1W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:1 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 2W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mssql' AND current_worker:2 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 2W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:2 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 2W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:2 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 4W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mssql' AND current_worker:4 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 4W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:4 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 4W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:4 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 8W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mssql' AND current_worker:8 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 8W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:8 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 8W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:8 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 16W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mssql' AND current_worker:16 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 16W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:16 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 16W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:16 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "pod 32W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tpm", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mssql' AND current_worker:32 AND kind:'pod' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "kata 32W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:32 AND kind:'kata' AND _exists_:tpm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm 32W",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:32 AND kind:'vm' AND _exists_:tpm",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Hammerdb MSSQL run artifacts",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 99 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "run_artifacts_url.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "version", "id": "1", "type": "max" }
     ],
     "query": "db_type:'mssql'",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Uperf norm ltcy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 }, "repeat": "Uperf_msg_size" },
  {
   "title": "Uperf: norm_ltcy",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 105 },
   "targets": [
    {
     "alias": "pod 64k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:1 AND kind:'pod' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 64k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:1 AND kind:'kata' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 64k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:1 AND kind:'vm' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 1024k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:1 AND kind:'pod' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 1024k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:1 AND kind:'kata' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 1024k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:1 AND kind:'vm' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 8192k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:1 AND kind:'pod' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 8192k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:1 AND kind:'kata' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 8192k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:1 AND kind:'vm' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 64 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:8 AND kind:'pod' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 64 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:8 AND kind:'kata' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 64 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:8 AND kind:'vm' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 1024k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:8 AND kind:'pod' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 1024k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:8 AND kind:'kata' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 1024k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:8 AND kind:'vm' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 8192k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:8 AND kind:'pod' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 8192k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:8 AND kind:'kata' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 8192k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:8 AND kind:'vm' AND test_type='rr'",
     "timeField": "uperf_ts"
    }
   ]
  },
  {
   "title": "Uperf: norm_ltcy (state timeline)",
   "type": "state-timeline",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 117 },
   "targets": [
    {
     "alias": "pod 64k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:1 AND kind:'pod' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 64k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:1 AND kind:'kata' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 64k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:1 AND kind:'vm' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 1024k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:1 AND kind:'pod' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 1024k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:1 AND kind:'kata' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 1024k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:1 AND kind:'vm' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 8192k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:1 AND kind:'pod' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 8192k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:1 AND kind:'kata' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 8192k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:1 AND kind:'vm' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 64k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:8 AND kind:'pod' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 64k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:8 AND kind:'kata' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 64k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:8 AND kind:'vm' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 1024k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:8 AND kind:'pod' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 1024k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:8 AND kind:'kata' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 1024 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:8 AND kind:'vm' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 8192k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:8 AND kind:'pod' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 8192k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:8 AND kind:'kata' AND test_type='rr'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 8192k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_ltcy", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:8 AND kind:'vm' AND test_type='rr'",
     "timeField": "uperf_ts"
    }
   ]
  },
  { "title": "Uperf norm byte", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 } },
  {
   "title": "Uperf: norm_byte",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 131 },
   "targets": [
    {
     "alias": "pod 64k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:1 AND kind:'pod' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 64k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:1 AND kind:'kata' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 64k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:1 AND kind:'vm' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 1024k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:1 AND kind:'pod' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 1024k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:1 AND kind:'kata' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 1024k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:1 AND kind:'vm' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 8192k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:1 AND kind:'pod' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 8192k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:1 AND kind:'kata' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 8192k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:1 AND kind:'vm' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 64 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:8 AND kind:'pod' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 64 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:8 AND kind:'kata' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 64 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:8 AND kind:'vm' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 1024k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:8 AND kind:'pod' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 1024k 8th",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:8 AND kind:'kata' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 1024k 8th",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:8 AND kind:'vm' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 8192k 8th",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:8 AND kind:'pod' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 8192k 8th",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:8 AND kind:'kata' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 8192k 8th",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:8 AND kind:'vm' AND test_type='stream'",
     "timeField": "uperf_ts"
    }
   ]
  },
  {
   "title": "Uperf: norm_byte(state timeline)",
   "type": "state-timeline",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 143 },
   "targets": [
    {
     "alias": "pod 64k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:1 AND kind:'pod' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 64k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:1 AND kind:'kata' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 64k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:1 AND kind:'vm' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 1024k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:1 AND kind:'pod' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 1024k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:1 AND kind:'kata' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 1024k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:1 AND kind:'vm' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 8192k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:1 AND kind:'pod' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 8192k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:1 AND kind:'kata' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 8192k 1th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:1 AND kind:'vm' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 64k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:8 AND kind:'pod' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 64k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:8 AND kind:'kata' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 64k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:64 AND num_threads:8 AND kind:'vm' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 1024k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:8 AND kind:'pod' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 1024k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:8 AND kind:'kata' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 1024 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:1024 AND num_threads:8 AND kind:'vm' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "pod 8192k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:8 AND kind:'pod' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "kata 8192k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:8 AND kind:'kata' AND test_type='stream'",
     "timeField": "uperf_ts"
    },
    {
     "alias": "vm 8192k 8th",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "avg" }
     ],
     "query": "read_message_size:8192 AND num_threads:8 AND kind:'vm' AND test_type='stream'",
     "timeField": "uperf_ts"
    }
   ]
  },
  {
   "title": "Uperf run artifacts",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 156 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "run_artifacts_url.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "version", "id": "1", "type": "max" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Stressng CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 161 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 162 },
   "options": { "content": "## Stressng workload results" },
   "targets": [
    {
     "alias": "TPM: 1 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:1",
     "timeField": "timestamp"
    },
    {
     "alias": "TPM: 2 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Stressng: CPU",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 164 },
   "targets": [
    {
     "alias": "pod",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu", "id": "1", "type": "max" }
     ],
     "query": "kind:'pod' ",
     "timeField": "timestamp"
    },
    {
     "alias": "kata",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm'",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Stressng: CPU (state timeline)",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 175 },
   "targets": [
    {
     "alias": "pod",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu", "id": "1", "type": "max" }
     ],
     "query": "kind:'pod' ",
     "timeField": "timestamp"
    },
    {
     "alias": "kata",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "cpu",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'kata' ",
     "timeField": "timestamp"
    },
    {
     "alias": "vm",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cpu", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' ",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Stressng Memcpy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 181 } },
  {
   "title": "Stressng: Memcpy",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 182 },
   "targets": [
    {
     "alias": "pod",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "memcpy", "id": "1", "type": "max" }
     ],
     "query": "kind:'pod'",
     "timeField": "timestamp"
    },
    {
     "alias": "kata",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "memcpy", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' ",
     "timeField": "timestamp"
    },
    {
     "alias": "vm",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "memcpy", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm'",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Stressng: Memcpy (state timeline)",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 193 },
   "targets": [
    {
     "alias": "pod",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "memcpy", "id": "1", "type": "max" }
     ],
     "query": "kind:'pod' ",
     "timeField": "timestamp"
    },
    {
     "alias": "kata",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "memcpy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'kata' ",
     "timeField": "timestamp"
    },
    {
     "alias": "vm",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "memcpy", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' ",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Stressng VM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 199 } },
  {
   "title": "Stressng: VM",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 200 },
   "targets": [
    {
     "alias": "pod",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "vm", "id": "1", "type": "max" }
     ],
     "query": "kind:'pod' ",
     "timeField": "timestamp"
    },
    {
     "alias": "kata",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "vm", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata'",
     "timeField": "timestamp"
    },
    {
     "alias": "vm",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "vm", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm'",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Stressng: VM  (state timeline)",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 211 },
   "targets": [
    {
     "alias": "pod",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "vm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' ",
     "timeField": "timestamp"
    },
    {
     "alias": "kata",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "vm", "id": "1", "type": "max" }
     ],
     "query": "kind:'kata' ",
     "timeField": "timestamp"
    },
    {
     "alias": "vm",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "vm", "id": "1", "type": "max" }
     ],
     "query": "kind:'vm' ",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Stressng run artifacts",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 217 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "run_artifacts_url.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "version", "id": "1", "type": "max" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 222 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 223 },
   "options": {
    "content": "![alt text](https://github.com/redhat-performance/benchmark-runner/blob/main/media/benchmark_runner.png?raw=true \"Tooltip Text\")"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 223 },
   "options": {
    "content": "![alt text](https://www.redhat.com/cms/managed-files/Brand_Standars-Red_Hat-_color_on-black.svg?itok=wPCF1-sX \"Tooltip Text\")"
   }
  }
 ]
}