{
 "title": "benchmark-runner-report-compare-3-ocp-versions",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ocp_version1",
    "label": "ocp_version1",
    "query": "{\"find\":\"terms\",\"field\":\"ci_date.keyword\"}"
   },
   {
    "name": "ocp_version2",
    "label": "ocp_version2",
    "query": "{\"find\":\"terms\",\"field\":\"ci_date.keyword\"}"
   },
   {
    "name": "ocp_version3",
    "label": "ocp_version3",
    "query": "{\"find\":\"terms\",\"field\":\"ci_date.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 0 },
   "options": {
    "content": "![alt text](https://github.com/redhat-performance/benchmark-runner/blob/main/media/benchmark_runner.png?raw=true \"Tooltip Text\")"
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 }, "options": { "content": "# Workloads  " } },
  { "title": "Hammerdb", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "build" },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 9 },
   "options": {
    "content": "## Hammerdb workload results\n![alt text](https://www.hammerdb.com/images/hammerDB-logo-FINAL.jpg \"Tooltip Text\")"
   },
   "targets": [
    {
     "alias": "TPM: 1 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:1",
     "timeField": "timestamp"
    },
    {
     "alias": "TPM: 2 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "options": {
    "content": "![alt text](https://seekvectorlogo.net/wp-content/uploads/2020/02/mariadb-vector-logo.png \"Tooltip Text\")"
   },
   "targets": [
    {
     "alias": "TPM: 1 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:1",
     "timeField": "timestamp"
    },
    {
     "alias": "TPM: 2 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "TPM: Hammerdb-Mariadb",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$ocp_version1: VM 2 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2 AND kind:'vm' AND ocp_version1=$ocp_version1",
     "timeField": "timestamp"
    },
    {
     "alias": "$ocp_version1: POD 2 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2 AND kind:'pod' AND ocp_version=$ocp_version1",
     "timeField": "timestamp"
    },
    {
     "alias": "$ocp_version2: VM 2 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2 AND kind:'vm' AND ocp_version=$ocp_version2",
     "timeField": "timestamp"
    },
    {
     "alias": "$ocp_version2: POD 2 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2 AND kind:'pod' AND ocp_version=$ocp_version2",
     "timeField": "timestamp"
    },
    {
     "alias": "$ocp_version3: VM 2 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2 AND kind:'vm' AND ocp_version=$ocp_version3",
     "timeField": "timestamp"
    },
    {
     "alias": "$ocp_version3: POD 2 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2 AND kind:'pod' AND ocp_version=$ocp_version3",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 19 },
   "options": {
    "content": "![alt text](https://miro.medium.com/max/2000/1*115cqXTggxGeZq5m-yFnrw.png \"Tooltip Text\")"
   },
   "targets": [
    {
     "alias": "TPM: 1 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:1",
     "timeField": "timestamp"
    },
    {
     "alias": "TPM: 2 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "TPM: Hammerdb-Postgresql ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$ocp_version1: VM: 2 Workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:2 AND kind:'vm' AND ocp_version=$ocp_version1",
     "timeField": "timestamp"
    },
    {
     "alias": "$ocp_version1: POD: 2 Workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:2 AND kind:'pod' AND ocp_version=$ocp_version1",
     "timeField": "timestamp"
    },
    {
     "alias": "$ocp_version2: VM: 2 Workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:2 AND kind:'vm' AND ocp_version=$ocp_version2",
     "timeField": "timestamp"
    },
    {
     "alias": "$ocp_version2: POD: 2 Workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:2 AND kind:'pod' AND ocp_version=$ocp_version2",
     "timeField": "timestamp"
    },
    {
     "alias": "$ocp_version3: VM: 2 Workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:2 AND kind:'vm' AND ocp_version=$ocp_version3",
     "timeField": "timestamp"
    },
    {
     "alias": "$ocp_version3: POD: 2 Workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:2 AND kind:'pod' AND ocp_version=$ocp_version3",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 26 },
   "options": {
    "content": "![alt text](https://surabaya.proxsisgroup.com/wp-content/uploads/2018/01/Microsoft-SQL-Server.png \"Tooltip Text\")"
   },
   "targets": [
    {
     "alias": "TPM: 1 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:1",
     "timeField": "timestamp"
    },
    {
     "alias": "TPM: 2 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "TPM: Hammerdb-MSSQL",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$ocp_version1: VM: 2 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:2 AND kind:’vm’ AND ocp_version=$ocp_version1",
     "timeField": "timestamp"
    },
    {
     "alias": "$ocp_version1: Pod: 2 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:2 AND kind:’pod’ AND ocp_version=$ocp_version1",
     "timeField": "timestamp"
    },
    {
     "alias": "$ocp_version2: VM: 2 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:2 AND kind:’vm’ AND ocp_version=$ocp_version2",
     "timeField": "timestamp"
    },
    {
     "alias": "$ocp_version2: Pod: 2 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:2 AND kind:’pod’ AND ocp_version=$ocp_version2",
     "timeField": "timestamp"
    },
    {
     "alias": "$ocp_version3: VM: 2 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:2 AND kind:’vm’ AND ocp_version=$ocp_version3",
     "timeField": "timestamp"
    },
    {
     "alias": "$ocp_version3 Pod: 2 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:2 AND kind:’pod’ AND ocp_version=$ocp_version3",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Uperf", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 36 },
   "options": { "content": "## Uperf workload results" },
   "targets": [
    {
     "alias": "TPM: 1 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:1",
     "timeField": "timestamp"
    },
    {
     "alias": "TPM: 2 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Uperf - norm_ltcy  - 1 thread",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$ocp_version1:  VM 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ltcy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'vm' AND num_threads:1 AND ocp_version=$ocp_version1",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version1:  POD 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ltcy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'pod' AND num_threads:1 AND ocp_version=$ocp_version1",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version2:  VM 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ltcy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'vm' AND num_threads:1 AND ocp_version=$ocp_version2",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version2:  POD 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ltcy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'pod' AND num_threads:1 AND ocp_version=$ocp_version2",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version3:  VM 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ltcy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'vm' AND num_threads:1 AND ocp_version=$ocp_version3",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version3:  POD 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ltcy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'pod' AND num_threads:1 AND ocp_version=$ocp_version3",
     "timeField": "uperf_ts"
    }
   ]
  },
  {
   "title": "Uperf - norm_ltcy - 2 threads",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$ocp_version1: VM  16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ltcy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'vm' AND num_threads:2 AND ocp_version=$ocp_version1",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version1: Pod  16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ltcy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'pod' AND num_threads:2 AND ocp_version=$ocp_version1",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version2: VM  16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ltcy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'vm' AND num_threads:2 AND ocp_version=$ocp_version2",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version2: POD  16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ltcy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'pod' AND num_threads:2 AND ocp_version=$ocp_version2",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version3: POD  16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ltcy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'vm' AND num_threads:2 AND ocp_version=$ocp_version3",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version3: POD  16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ltcy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'pod' AND num_threads:2 AND ocp_version=$ocp_version3",
     "timeField": "uperf_ts"
    }
   ]
  },
  {
   "title": "Uperf - norm_ops  - 1 thread",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$ocp_version1: VM 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ops",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'vm' AND num_threads:1 AND ocp_version=$ocp_version1",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version1: POD 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ops",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'pod' AND num_threads:1 AND ocp_version=$ocp_version1",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version2: VM 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ops",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'vm' AND num_threads:1 AND ocp_version=$ocp_version2",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version2: POD 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ops",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'pod' AND num_threads:1 AND ocp_version=$ocp_version2",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version3: VM 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ops",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'vm' AND num_threads:1 AND ocp_version=$ocp_version3",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version3: POD 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ops",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'pod' AND num_threads:1 AND ocp_version=$ocp_version3",
     "timeField": "uperf_ts"
    }
   ]
  },
  {
   "title": "Uperf - norm_ops  - 2 threads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$ocp_version1: VM 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ops",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'vm' AND num_threads:2 AND ocp_version=$ocp_version1",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version1: POD 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ops",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'pod' AND num_threads:2 AND ocp_version=$ocp_version1",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version2: VM 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ops",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'vm' AND num_threads:2 AND ocp_version=$ocp_version2",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version2: POD 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ops",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'pod' AND num_threads:2 AND ocp_version=$ocp_version2",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version3: VM 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ops",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'vm' AND num_threads:2 AND ocp_version=$ocp_version3",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version3: POD 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ops",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'pod' AND num_threads:2 AND ocp_version=$ocp_version3",
     "timeField": "uperf_ts"
    }
   ]
  },
  {
   "title": "Uperf - norm_bytes - 1 thread",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$ocp_version1: VM 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_byte",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'vm' AND num_threads:1 AND ocp_version=$ocp_version1",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version1: POD 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_byte",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'pod' AND num_threads:1 AND ocp_version=$ocp_version1",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version2: VM 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_byte",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'vm' AND num_threads:1 AND ocp_version=$ocp_version2",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version2: POD 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_byte",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'pod' AND num_threads:1 AND ocp_version=$ocp_version2",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version3: VM 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_byte",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'vm' AND num_threads:1 AND ocp_version=$ocp_version3",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version3: POD 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_byte",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'pod' AND num_threads:1 AND ocp_version=$ocp_version3",
     "timeField": "uperf_ts"
    }
   ]
  },
  {
   "title": "Uperf - norm_bytes - 2 threads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$ocp_version1: VM 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "max" }
     ],
     "query": "read_message_size:16384 AND kind:'vm' AND num_threads:2 AND ocp_version=$ocp_version1",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version1: POD 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "max" }
     ],
     "query": "read_message_size:16384 AND kind:'pod' AND num_threads:2 AND ocp_version=$ocp_version1",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version2: VM 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "max" }
     ],
     "query": "read_message_size:16384 AND kind:'vm' AND num_threads:2 AND ocp_version=$ocp_version2",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version2: POD 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "max" }
     ],
     "query": "read_message_size:16384 AND kind:'pod' AND num_threads:2 AND ocp_version=$ocp_version2",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version3: VM 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "max" }
     ],
     "query": "read_message_size:16384 AND kind:'vm' AND num_threads:2 AND ocp_version=$ocp_version3",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version3: POD 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "norm_byte", "id": "1", "type": "max" }
     ],
     "query": "read_message_size:16384 AND kind:'pod' AND num_threads:2 AND ocp_version=$ocp_version3",
     "timeField": "uperf_ts"
    }
   ]
  },
  {
   "title": "Uperf - read message size - 1 thread",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$ocp_version1: VM 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read_message_size",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'vm' AND num_threads:1 AND ocp_version=$ocp_version1",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version1: POD 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read_message_size",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'pod' AND num_threads:1 AND ocp_version=$ocp_version1",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version2: VM 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read_message_size",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'vm' AND num_threads:1 AND ocp_version=$ocp_version2",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version2: POD 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read_message_size",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'pod' AND num_threads:1 AND ocp_version=$ocp_version2",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version3: VM 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read_message_size",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'vm' AND num_threads:1 AND ocp_version=$ocp_version3",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version3: POD 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read_message_size",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'pod' AND num_threads:1 AND ocp_version=$ocp_version3",
     "timeField": "uperf_ts"
    }
   ]
  },
  {
   "title": "Uperf - read message size - 2 threads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$ocp_version1: VM 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read_message_size",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'vm' AND num_threads:2 AND ocp_version=$ocp_version1",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version1: POD 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read_message_size",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'pod' AND num_threads:2 AND ocp_version=$ocp_version1",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version2: VM 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read_message_size",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'vm' AND num_threads:2 AND ocp_version=$ocp_version2",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version2: POD 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read_message_size",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'pod' AND num_threads:2 AND ocp_version=$ocp_version2",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version3: VM 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read_message_size",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'vm' AND num_threads:2 AND ocp_version=$ocp_version3",
     "timeField": "uperf_ts"
    },
    {
     "alias": "$ocp_version3: POD 16384",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read_message_size",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 AND kind:'pod' AND num_threads:2 AND ocp_version=$ocp_version3",
     "timeField": "uperf_ts"
    }
   ]
  },
  { "title": "Stressng", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 121 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 122 },
   "options": { "content": "## Stressng workload results" },
   "targets": [
    {
     "alias": "TPM: 1 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:1",
     "timeField": "timestamp"
    },
    {
     "alias": "TPM: 2 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Stressng - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$ocp_version1: VM CPU ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "cpu",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'vm' AND ocp_version=$ocp_version1",
     "timeField": "timestamp"
    },
    {
     "alias": "$ocp_version1: POD CPU",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "cpu",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND ocp_version=$ocp_version1",
     "timeField": "timestamp"
    },
    {
     "alias": "$ocp_version2: VM CPU",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "cpu",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'vm' AND ocp_version=$ocp_version2",
     "timeField": "timestamp"
    },
    {
     "alias": "$ocp_version2: POD CPU",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "cpu",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND ocp_version=$ocp_version2",
     "timeField": "timestamp"
    },
    {
     "alias": "$ocp_version3: VM CPU",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "cpu",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'vm' AND ocp_version=$ocp_version3",
     "timeField": "timestamp"
    },
    {
     "alias": "$ocp_version3: POD CPU",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "cpu",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND ocp_version=$ocp_version3",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Stressng - Memcpy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$ocp_version1: VM Memcpy ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "memcpy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'vm' AND ocp_version=$ocp_version1",
     "timeField": "timestamp"
    },
    {
     "alias": "$ocp_version1: POD Memcpy",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "memcpy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND ocp_version=$ocp_version1",
     "timeField": "timestamp"
    },
    {
     "alias": "$ocp_version2: VM Memcpy",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "memcpy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'vm' AND ocp_version=$ocp_version2",
     "timeField": "timestamp"
    },
    {
     "alias": "$ocp_version2: POD Memcpy",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "memcpy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND ocp_version=$ocp_version2",
     "timeField": "timestamp"
    },
    {
     "alias": "$ocp_version3: VM Memcpy",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "memcpy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'vm' AND ocp_version=$ocp_version3",
     "timeField": "timestamp"
    },
    {
     "alias": "$ocp_version3: POD Memcpy",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "memcpy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND ocp_version=$ocp_version3",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Stressng - VM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 140 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$ocp_version1: VM VM ",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "vm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'vm' AND ocp_version=$ocp_version1",
     "timeField": "timestamp"
    },
    {
     "alias": "$ocp_version1: POD VM",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "vm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND ocp_version=$ocp_version1",
     "timeField": "timestamp"
    },
    {
     "alias": "$ocp_version2: VM VM",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "vm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'vm' AND ocp_version=$ocp_version2",
     "timeField": "timestamp"
    },
    {
     "alias": "$ocp_version2: POD VM",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "vm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND ocp_version=$ocp_version2",
     "timeField": "timestamp"
    },
    {
     "alias": "$ocp_version3: VM VM",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "vm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'vm' AND ocp_version=$ocp_version3",
     "timeField": "timestamp"
    },
    {
     "alias": "$ocp_version3: POD VM",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "vm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind:'pod' AND ocp_version=$ocp_version3",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 148 },
   "options": {
    "content": "![alt text](https://www.redhat.com/cms/managed-files/Brand_Standars-Red_Hat-_color_on-black.svg?itok=wPCF1-sX \"Tooltip Text\")"
   }
  }
 ]
}