{
 "title": "benchmark-runner report",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "runner_version",
    "label": "runner version",
    "query": "{\"find\":\"terms\",\"field\":\"runner version.keyword\"}"
   },
   {
    "name": "uuid",
    "label": "uuid",
    "query": "{\"find\":\"terms\",\"field\":\"uuid.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 0 },
   "options": {
    "content": "![alt text](https://github.com/redhat-performance/benchmark-runner/blob/main/media/benchmark_runner.png?raw=true \"Tooltip Text\")"
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 }, "options": { "content": "# Workloads  " } },
  { "title": "Hammerdb", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "build" },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 9 },
   "options": { "content": "## Hammerdb workload results" },
   "targets": [
    {
     "alias": "TPM: 1 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:1",
     "timeField": "timestamp"
    },
    {
     "alias": "TPM: 2 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
   "options": {
    "content": "![alt text](https://seekvectorlogo.net/wp-content/uploads/2020/02/mariadb-vector-logo.png \"Tooltip Text\")"
   },
   "targets": [
    {
     "alias": "TPM: 1 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:1",
     "timeField": "timestamp"
    },
    {
     "alias": "TPM: 2 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "TPM: Hammerdb-Mariadb",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "VM: 1 worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:1 AND kind:'vm'",
     "timeField": "timestamp"
    },
    {
     "alias": "Pod: 1 worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:1 AND kind:'pod'",
     "timeField": "timestamp"
    },
    {
     "alias": "VM: 2 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2 AND kind:'vm'",
     "timeField": "timestamp"
    },
    {
     "alias": "Pod: 2 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2 AND kind:'pod'",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
   "options": {
    "content": "![alt text](https://miro.medium.com/max/2000/1*115cqXTggxGeZq5m-yFnrw.png \"Tooltip Text\")"
   },
   "targets": [
    {
     "alias": "TPM: 1 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:1",
     "timeField": "timestamp"
    },
    {
     "alias": "TPM: 2 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "TPM: Hammerdb-Postgresql ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "VM: 1 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:1 AND kind:'vm'",
     "timeField": "timestamp"
    },
    {
     "alias": "Pod: 1 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:1 AND kind:'pod'",
     "timeField": "timestamp"
    },
    {
     "alias": "VM: 2 Workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:2 AND kind:'vm'",
     "timeField": "timestamp"
    },
    {
     "alias": "Pod: 2 Workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'pg' AND current_worker:2 AND kind:'pod'",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "options": {
    "content": "![alt text](https://surabaya.proxsisgroup.com/wp-content/uploads/2018/01/Microsoft-SQL-Server.png \"Tooltip Text\")"
   },
   "targets": [
    {
     "alias": "TPM: 1 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:1",
     "timeField": "timestamp"
    },
    {
     "alias": "TPM: 2 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "TPM: Hammerdb-MSSQL",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "VM: 1 worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:1 AND kind:’vm’",
     "timeField": "timestamp"
    },
    {
     "alias": "Pod: 1 worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:1 AND kind:’pod’",
     "timeField": "timestamp"
    },
    {
     "alias": "VM: 2 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:2 AND kind:’vm’",
     "timeField": "timestamp"
    },
    {
     "alias": "Pod: 2 workers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mssql' AND current_worker:2 AND kind:’pod’",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Uperf", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 34 },
   "options": { "content": "## Uperf workload results" },
   "targets": [
    {
     "alias": "TPM: 1 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:1",
     "timeField": "timestamp"
    },
    {
     "alias": "TPM: 2 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Uperf - norm_ltcy",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "64 vm",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ltcy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:64 and kind=vm",
     "timeField": "uperf_ts"
    },
    {
     "alias": "64 pod",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ltcy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:64 and kind=pod",
     "timeField": "uperf_ts"
    },
    {
     "alias": "256 vm",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ltcy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:256 and kind=vm",
     "timeField": "uperf_ts"
    },
    {
     "alias": "256 pod",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ltcy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:256 and kind=pod",
     "timeField": "uperf_ts"
    },
    {
     "alias": "1024 vm",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ltcy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:1024 and kind=vm",
     "timeField": "uperf_ts"
    },
    {
     "alias": "1024 pod",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ltcy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:1024 and kind=pod",
     "timeField": "uperf_ts"
    },
    {
     "alias": "4096 vm",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ltcy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:4096 and kind=vm",
     "timeField": "uperf_ts"
    },
    {
     "alias": "4096 pod",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ltcy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:4096 and kind=pod",
     "timeField": "uperf_ts"
    },
    {
     "alias": "16384 vm",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ltcy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 and kind=vm",
     "timeField": "uperf_ts"
    },
    {
     "alias": "16384 pod",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ltcy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 and kind=pod",
     "timeField": "uperf_ts"
    }
   ]
  },
  {
   "title": "Uperf - norm_ops",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "64 vm",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ops",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:64 and kind=vm",
     "timeField": "uperf_ts"
    },
    {
     "alias": "64 pod",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ops",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:64 and kind=pod",
     "timeField": "uperf_ts"
    },
    {
     "alias": "256 vm",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ops",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:256 and kind=vm",
     "timeField": "uperf_ts"
    },
    {
     "alias": "256 pod",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ops",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:256 and kind=pod",
     "timeField": "uperf_ts"
    },
    {
     "alias": "1024 vm",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ops",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:1024 and kind=vm",
     "timeField": "uperf_ts"
    },
    {
     "alias": "1024 pod",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ops",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:1024 and kind=pod",
     "timeField": "uperf_ts"
    },
    {
     "alias": "4096 vm",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ops",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:4096 and kind=vm",
     "timeField": "uperf_ts"
    },
    {
     "alias": "4096 pod",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ops",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:4096 and kind=pod",
     "timeField": "uperf_ts"
    },
    {
     "alias": "16384 vm",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ops",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 and kind=vm",
     "timeField": "uperf_ts"
    },
    {
     "alias": "16384 pod",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_ops",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 and kind=pod",
     "timeField": "uperf_ts"
    }
   ]
  },
  {
   "title": "Uperf - norm_bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "64 vm",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_byte",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:64 and kind=vm",
     "timeField": "uperf_ts"
    },
    {
     "alias": "64 pod",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_byte",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:64 and kind=pod",
     "timeField": "uperf_ts"
    },
    {
     "alias": "256 vm",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_byte",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:256 and kind=vm",
     "timeField": "uperf_ts"
    },
    {
     "alias": "256 pod",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_byte",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:256 and kind=pod",
     "timeField": "uperf_ts"
    },
    {
     "alias": "1024 vm",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_byte",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:1024 and kind=vm",
     "timeField": "uperf_ts"
    },
    {
     "alias": "1024 pod",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_byte",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:1024 and kind=pod",
     "timeField": "uperf_ts"
    },
    {
     "alias": "4096 vm",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_byte",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:4096 and kind=vm",
     "timeField": "uperf_ts"
    },
    {
     "alias": "4096 pod",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_byte",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:4096 and kind=pod",
     "timeField": "uperf_ts"
    },
    {
     "alias": "16384 vm",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_byte",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 and kind=vm",
     "timeField": "uperf_ts"
    },
    {
     "alias": "16384 pod",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_byte",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 and kind=pod",
     "timeField": "uperf_ts"
    }
   ]
  },
  {
   "title": "Uperf - read message size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "64 vm",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read_message_size",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:64 and kind=vm",
     "timeField": "uperf_ts"
    },
    {
     "alias": "64 pod",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read_message_size",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:64 and kind=pod",
     "timeField": "uperf_ts"
    },
    {
     "alias": "256 vm",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read_message_size",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:256 and kind=vm",
     "timeField": "uperf_ts"
    },
    {
     "alias": "256 pod",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read_message_size",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:256 and kind=pod",
     "timeField": "uperf_ts"
    },
    {
     "alias": "1024 vm",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read_message_size",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:1024 and kind=vm",
     "timeField": "uperf_ts"
    },
    {
     "alias": "1024 pod",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read_message_size",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:1024 and kind=pod",
     "timeField": "uperf_ts"
    },
    {
     "alias": "4096 vm",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read_message_size",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:4096 and kind=vm",
     "timeField": "uperf_ts"
    },
    {
     "alias": "4096 pod",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read_message_size",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:4096 and kind=pod",
     "timeField": "uperf_ts"
    },
    {
     "alias": "16384 vm",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read_message_size",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 and kind=vm",
     "timeField": "uperf_ts"
    },
    {
     "alias": "16384 pod",
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read_message_size",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "read_message_size:16384 and kind=pod",
     "timeField": "uperf_ts"
    }
   ]
  },
  { "title": "Stressng", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 79 },
   "options": { "content": "## Stressng workload results" },
   "targets": [
    {
     "alias": "TPM: 1 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:1",
     "timeField": "timestamp"
    },
    {
     "alias": "TPM: 2 Worker",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tpm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "db_type:'mariadb' AND current_worker:2",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Stressng",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "CPU VM",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "cpu",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind=vm",
     "timeField": "timestamp"
    },
    {
     "alias": "CPU Pod",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "cpu",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind=pod",
     "timeField": "timestamp"
    },
    {
     "alias": "memcpy VM",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "memcpy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind=vm",
     "timeField": "timestamp"
    },
    {
     "alias": "memcpy Pod",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "memcpy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind=pod",
     "timeField": "timestamp"
    },
    {
     "alias": "vm VM",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "vm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind=vm",
     "timeField": "timestamp"
    },
    {
     "alias": "vm Pod",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "vm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kind=pod",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 89 },
   "options": {
    "content": "![alt text](https://www.redhat.com/cms/managed-files/Brand_Standars-Red_Hat-_color_on-black.svg?itok=wPCF1-sX \"Tooltip Text\")"
   }
  }
 ]
}