apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  annotations:
    cdi.kubevirt.io/storage.deleteAfterCompletion: "false"
    {%- if per_node_dv and scale_node %}
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
    volume.kubernetes.io/selected-node: {{ scale_node }}
    {%- endif %}
  name: {{ dv_source_name }}
  namespace: {{ namespace }}
spec:
  source:
    {%- if cdi_source_type == 's3' %}
    s3:
      url: {{ url }}
      {%- if cdi_source_s3_cred %}
      secretRef: {{ cdi_source_s3_cred }}
      {%- endif %}
    {%- else %}
    http:
      url: {{ url }}
    {%- endif %}
  pvc:
    accessModes:
      - {{ vm_access_mode }}
    resources:
      requests:
        storage: {{ storage }}
    volumeMode: Block
    storageClassName: {{ vm_storage_class }}
