apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  {% if scale -%}
  name: winfio-{{ kind }}-{{ trunc_uuid }}-{{ scale }}
  labels:
    kubevirt.io/vm: winfio-{{ kind }}-{{ trunc_uuid }}-{{ scale }}
  {%- else -%}
  name:  winfio-{{ kind }}-{{ trunc_uuid }}
  labels:
    kubevirt.io/vm: winfio-{{ kind }}-{{ trunc_uuid }}
  {%- endif %}
  namespace: {{ namespace }}
spec:
  {% if run_strategy -%}
  runStrategy: Always
  {%- else -%}
  running: false
  {%- endif %}
  template:
    metadata:
      labels:
        {% if scale -%}
        kubevirt.io/vm: winfio-{{ kind }}-{{ trunc_uuid }}-{{ scale }}
        {%- else -%}
        kubevirt.io/vm: winfio-{{ kind }}-{{ trunc_uuid }}
        {%- endif %}
    spec:
      terminationGracePeriodSeconds: 0
      evictionStrategy: LiveMigrate
      domain:
        firmware:
          bootloader:
            efi:
              secureBoot: false
        clock:
          timer:
            hpet:
              present: false
            hyperv: {}
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
          utc: {}
        cpu:
          cores: 1
          model: host-passthrough
          sockets: {{ sockets }}
          threads: 1
        devices:
          blockMultiQueue: false
          disks:
          - disk:
              bus: virtio
            {% if scale -%}
            name: winfio-{{ kind }}-root-disk-{{ trunc_uuid }}-{{ scale }}
            {%- else -%}
            name: winfio-{{ kind }}-root-disk-{{ trunc_uuid }}
            {%- endif %}
            dedicatedIOThread: false
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            model: virtio
            name: nic-0
            networkInterfaceMultiqueue: true
            tpm: { }
        features:
          acpi: {}
          apic: {}
          hyperv:
            frequencies: {}
            ipi: {}
            reenlightenment: {}
            tlbflush: {}
            relaxed: {}
            reset: {}
            runtime: {}
            spinlocks:
              spinlocks: 8191
            synic: {}
            synictimer:
                direct: {}
            vapic: {}
            vpindex: {}
          smm: {}
        machine:
          type: q35
        resources:
          requests:
            cpu: {{ requests_cpu }}
            memory: {{ requests_memory }}
      networks:
      - name: nic-0
        pod: {}
      volumes:
      - dataVolume:
          {% if scale -%}
          name: winfio-{{ kind }}-root-disk-{{ trunc_uuid }}-{{ scale }}
          {%- else -%}
          name: winfio-{{ kind }}-root-disk-{{ trunc_uuid }}
          {%- endif %}
        {% if scale -%}
        name: winfio-{{ kind }}-root-disk-{{ trunc_uuid }}-{{ scale }}
        {%- else -%}
        name: winfio-{{ kind }}-root-disk-{{ trunc_uuid }}
        {%- endif %}
      - cloudInitNoCloud:
          userData: |
            #cloud-config
            runcmd:
              - powershell -Command "New-Item -ItemType Directory -Force -Path 'C:\ProgramData\ssh' | Out-Null; Set-Content -Path 'C:\ProgramData\ssh\administrators_authorized_keys' -Value '{{ ssh_public_key }}' -Encoding ascii -Force; icacls 'C:\ProgramData\ssh\administrators_authorized_keys' /inheritance:r /grant 'Administrators:F' /grant 'SYSTEM:F'"
              - cmd /c "mkdir C:\Users\Administrator\.ssh >nul 2>&1 & icacls C:\Users\Administrator\.ssh /grant Everyone:F >nul 2>&1 & takeown /f C:\Users\Administrator\.ssh\authorized_keys >nul 2>&1 & icacls C:\Users\Administrator\.ssh\authorized_keys /grant Everyone:F >nul 2>&1 & del /f C:\Users\Administrator\.ssh\authorized_keys >nul 2>&1"
              - powershell -Command "Copy-Item 'C:\ProgramData\ssh\administrators_authorized_keys' 'C:\Users\Administrator\.ssh\authorized_keys' -Force; icacls 'C:\Users\Administrator\.ssh\authorized_keys' /inheritance:r /grant 'Administrators:F' /grant 'SYSTEM:F'; icacls 'C:\Users\Administrator\.ssh' /inheritance:r /grant 'Administrators:F' /grant 'SYSTEM:F'"
        name: cloudinitdisk
  dataVolumeTemplates:
  - metadata:
      annotations:
        descheduler.alpha.kubernetes.io/evict: "true"
      {% if scale -%}
      name: winfio-{{ kind }}-root-disk-{{ trunc_uuid }}-{{ scale }}
      {%- else -%}
      name: winfio-{{ kind }}-root-disk-{{ trunc_uuid }}
      {%- endif %}
    spec:
      pvc:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: {{ storage }}
        volumeMode: Block
        storageClassName: ocs-storagecluster-ceph-rbd-virtualization
      source:
        pvc:
          namespace: {{ namespace }}
          name: windows-clone-dv
