apiVersion: v1
kind: Namespace
metadata:
  name: mariadb-db
---
{%- if kind == 'kata' %}
#This is a tweak of the restricted scc, to allow fsGroup to be specified in a deployment
# workaround for kata virtiofsd permission error in ODF 4.10.5
apiVersion: security.openshift.io/v1
metadata:
  name: mariadbscc
kind: SecurityContextConstraints
fsGroup:
  type: RunAsAny
runAsUser:
  type: MustRunAsRange
seLinuxContext:
  type: MustRunAs
users:
- system:serviceaccount:mariadb-db:default
---
{%- endif %}
{%- if storage_type == 'lso' %}
apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: local-disks
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ lso_node }}
  storageClassDevices:
    - storageClassName: local-sc
      volumeMode: Filesystem
      fsType: ext4
      devicePaths:
        - /dev/disk/by-id/{{ lso_disk_id }}
---
{%- endif %}
{%- if storage_type == 'lso' or  odf_pvc == True %}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: mariadb-persistent-storage
    namespace: mariadb-db
spec:
    {%- if storage_type == 'lso' %}
    storageClassName: local-sc
    {%- else %}
    storageClassName: ocs-storagecluster-ceph-rbd
    {%- endif %}
    accessModes: [ "ReadWriteOnce" ]
    volumeMode: Filesystem
    resources:
      requests:
        storage: {{ storage }}
---
{%- endif %}
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-custom-config
  namespace: mariadb-db
data:
  custom.conf: |
        # This group is read both both by the client and the server
        # use it for options that affect everything
        #
        [client-server]
        !includedir /etc/my.cnf.d
        port=3306
        ssl=0

        [mysqld]
        key_buffer_size = 1638M
        max_allowed_packet = 200M
        table_open_cache = 400
        sort_buffer_size = 256K
        read_buffer_size = 16M   # safer per-connection buffer
        read_rnd_buffer_size = 256K
        net_buffer_length = 2K
        thread_stack = 256K
        myisam_sort_buffer_size = 2M
        max_connections = 151

        innodb_buffer_pool_size = 8192M
        innodb_log_file_size = 2457M
        innodb_log_buffer_size = 2457M
        innodb_file_per_table = 1
        innodb_flush_method = O_DIRECT
        innodb_adaptive_flushing = 1

        [mysqldump]
        quick
        max_allowed_packet = 16M

        [mysql]
        no-auto-rehash

        [myisamchk]
        key_buffer_size = 8M
        sort_buffer_size = 8M
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  namespace: mariadb-db
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
        type: mariadb-database-server
      {%- if kind == 'kata' and kata_cpuoffline_workaround == True %}
      annotations:
        io.katacontainers.config.hypervisor.default_vcpus: "{{ database_limits_cpu }}"
      {%- endif %}
    spec:
      nodeSelector:
        kubernetes.io/hostname: "{{ pin_node2 }}"
      {%- if kind == 'kata' %}
      runtimeClassName: kata
      # workaround for kata virtiofsd permission error in ODF 4.10.5
      securityContext:
        fsGroup: 0
      {%- endif %}
      terminationGracePeriodSeconds: 10
      containers:
      - name: mariadb
        # quay.io/sclorg/mariadb-105-c9s:latest - rate limit issue
        image: quay.io/benchmark-runner/mariadb10.5-centos9:latest
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 3306
        resources:
          requests:
            cpu: {{ database_requests_cpu }}
            memory: {{ database_requests_memory }}
          limits:
          {%- if kind != 'kata' or kata_cpuoffline_workaround != True %}
            cpu: {{ database_limits_cpu }}
            {%- endif %}
            memory: {{ database_limits_memory }}
        env:
           - name: MYSQL_USER
             value: "test"
           - name: MYSQL_PASSWORD
             value: "test"
           - name: MYSQL_ROOT_PASSWORD
             value: "mysql"
        volumeMounts:
          - name: mariadb-custom-config
            mountPath: /etc/my.cnf
            subPath: custom.conf #should be the name used in the ConfigMap
          {%- if storage_type == 'lso' or odf_pvc == True %}
          - name: mariadb-persistent-storage
            mountPath: /var/lib/mysql
            readOnly: false
          {%- endif %}
      volumes:
        - name: mariadb-custom-config
          configMap:
            name: mariadb-custom-config
        {%- if storage_type == 'lso' or odf_pvc == True %}
        - name: mariadb-persistent-storage
          persistentVolumeClaim:
            claimName: mariadb-persistent-storage
        {%- endif %}
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-deployment
  namespace: mariadb-db
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
