
# container CPU/Memory

- query: (sum(irate(container_cpu_usage_seconds_total{container!="",namespace="benchmark-runner", mode!="idle"}[2m])) by (node)) > 0
  metricName: containerCPU-benchmark-runner

- query: sum(container_memory_rss{namespace="benchmark-runner"} and on (node) kube_node_role{role="worker"}) by (node) > 0
  metricName: containerMemory-benchmark-runner


