apiVersion: v1
kind: Namespace
metadata:
  name: {{ kata_namespace }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-sandboxed-containers-operator
  namespace: {{ kata_namespace }}
spec:
  targetNamespaces:
  - {{ kata_namespace }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: sandboxed-containers-operator
  namespace: {{ kata_namespace }}
spec:
  channel: "{{ kata_channel }}"
  installPlanApproval: Automatic
  name: sandboxed-containers-operator
  source: {{ kata_catalog_source }}
  sourceNamespace: openshift-marketplace
  startingCSV: {{ kata_csv }}
