apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: odf-operator
  namespace: openshift-storage
spec:
  channel: "stable-{{ odf_version }}"
  installPlanApproval: Automatic
  name: odf-operator
  source: "{% if odf_version.split('.')[1] | int >= 21 %}redhat-operators-v{{ odf_version | replace('.', '') }}{% else %}redhat-operators{% endif %}"
  sourceNamespace: openshift-marketplace
