apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: odf-operator
  namespace: openshift-storage
spec:
  channel: "stable-{{ odf_version }}"
  installPlanApproval: Manual
  name: odf-operator
  source: redhat-operators-v49  # <-- Modify the name of the redhat-operators catalogsource to be correct for your cluster
  sourceNamespace: openshift-marketplace